// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Checkbox } from "widgets/checkbox.slint";

export component TestCase inherits Rectangle {
    out property <bool> checkbox-a-checked <=> checkbox-a.checked;
    out property <bool> checkbox-b-checked <=> checkbox-b.checked;
    out property <string> checkbox-a-state;
    out property <string> checkbox-b-state;

    public function toggle-a() {
        checkbox-a.toggle();
    }

    public function focus-a() {
        checkbox-a.focus();
    }

    public function focus-b() {
        checkbox-b.focus();
    }

    checkbox-a := Checkbox {
        toggled => {
            checkbox-a-state += "a";
        }
    }

    checkbox-b := Checkbox {
        enabled: false;
        toggled => {
            checkbox-b-state += "a";
        }
    }
}

/*
use i_slint_backend_testing::{AccessibleRole,ElementHandle};
use slint::{platform::Key,SharedString};

let instance = TestCase::new().unwrap();

let mut result = ElementHandle::find_by_element_id(&instance, "TestCase::checkbox-a").collect::<Vec<_>>();
assert_eq!(result.len(), 1);
let checkbox_a = result.pop().unwrap();

assert_eq!(checkbox_a.accessible_role().unwrap(), AccessibleRole::Checkbox);
assert!(checkbox_a.accessible_expanded().is_none());
assert!(checkbox_a.accessible_expandable().is_none());
assert!(checkbox_a.accessible_checkable().unwrap());
assert!(checkbox_a.accessible_enabled().unwrap());
assert!(!checkbox_a.accessible_checked().unwrap());

instance.invoke_focus_a();
i_slint_backend_testing::send_keyboard_string_sequence(&instance, &SharedString::from(Key::Space));
assert_eq!(instance.get_checkbox_a_checked(), true);
assert_eq!(instance.get_checkbox_a_state(), "a");
i_slint_backend_testing::send_keyboard_string_sequence(&instance, &SharedString::from(Key::Space));
assert_eq!(instance.get_checkbox_a_checked(), false);
assert_eq!(instance.get_checkbox_a_state(), "aa");

instance.invoke_toggle_a();
assert_eq!(instance.get_checkbox_a_checked(), true);
instance.invoke_toggle_a();
assert_eq!(instance.get_checkbox_a_checked(), false);

checkbox_a.invoke_accessible_default_action();
assert_eq!(instance.get_checkbox_a_checked(), true);
assert_eq!(instance.get_checkbox_a_state(), "aaa");
checkbox_a.invoke_accessible_default_action();
assert_eq!(instance.get_checkbox_a_checked(), false);
assert_eq!(instance.get_checkbox_a_state(), "aaaa");

let mut result = ElementHandle::find_by_element_id(&instance, "TestCase::checkbox-b").collect::<Vec<_>>();
assert_eq!(result.len(), 1);
let checkbox_b = result.pop().unwrap();

assert!(!checkbox_b.accessible_enabled().unwrap());

instance.invoke_focus_b();
i_slint_backend_testing::send_keyboard_string_sequence(&instance, &SharedString::from(Key::Space));
assert_eq!(instance.get_checkbox_b_checked(), false);
assert_eq!(instance.get_checkbox_b_state(), "");

checkbox_b.invoke_accessible_default_action();
assert_eq!(instance.get_checkbox_b_checked(), false);
assert_eq!(instance.get_checkbox_b_state(), "");
*/
