[workspace]
resolver = "3"
members = ["crates/core","crates/mukwa","crates/utils"]

[workspace.package]
version = "0.1.0-alpha.6"
edition = "2024"

# [[bench]]
# name = "service"
# harness = false

# [[bench]]
# name = "fmt"
# harness = false

[workspace.dependencies]
tracing = "0.1.44"
tempfile = "3.27.0"
jiff = "0.2.29"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.4", features = ["v7"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
clap = { version = "4.6.1", features = ["derive"] }
dirs = "6.0.0"
tracing-appender = "0.2.5"
rust-embed = "8.12.0"
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
fontdb = "0.24.0"
tiny-skia = "0.12.0"
image = "0.25.10"


[workspace.dependencies.slint]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"
features = ["backend-winit", "renderer-skia", "log"]

# [dev-dependencies]
# divan = "0.1.21"
