[package]
name = "mukwa"
version = "0.1.0-alpha.6"
edition = "2024"
default-run = "mukwa"

[[bench]]
name = "service"
harness = false

[[bench]]
name = "fmt"
harness = false

[[bin]]
name = "mukwa"
path = "src/bin/main.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[dependencies]
tracing = "0.1.44"
tempfile = "3.27.0"
jiff = "0.2.29"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.4", features = ["v7"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
clap = { version = "4.6.1", features = ["derive"] }
dirs = "6.0.0"
tracing-appender = "0.2.5"
rust-embed = "8.12.0"
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
fontdb = "0.24.0"
tiny-skia = "0.12.0"
raqote = "0.8.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8.7"
core-foundation = "0.10.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Globalization"] }

[dependencies.slint]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"
features = ["backend-winit", "renderer-skia", "log"]

[build-dependencies]
slint-build = { version = "1.16.0", git = "https://github.com/snubwoody/slint.git", branch = "mukwa" }
winresource = "0.1.31"
lucide-slint = "1.24.0"

[dev-dependencies]
divan = "0.1.21"
