[package]
name = "mukwa"
version = "0.1.0-alpha.6"
edition = "2024"

[dev-dependencies.i-slint-backend-testing]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"

[build-dependencies]
slint-build = { version = "1.16.0", git = "https://github.com/snubwoody/slint.git", branch = "mukwa" }
winresource = "0.1.31"
lucide-slint = "1.24.0"
