[package]
name = "tests"
version.workspace = true
edition.workspace = true

# Skia can't be built in flatpak because the binaries cannot be downloaded
[target.'cfg(target_os = "linux")'.dependencies.slint]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"
features = ["backend-winit", "renderer-femtovg", "log"]

[target.'cfg(not(target_os = "linux"))'.dependencies.slint]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"
features = ["backend-winit", "renderer-femtovg", "log"]

[dependencies.i-slint-backend-testing]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"
features = ["internal"]

[build-dependencies]
smol = "2.0.2"
lucide-slint = "1.24.0"

[build-dependencies.i-slint-compiler]
git = "https://github.com/snubwoody/slint.git"
branch = "mukwa"
version = "1.17.0"
features = ["rust","display-diagnostics"]
