// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "../colors.slint";
import { FocusBorder } from "./focus-border.slint";

export component Button inherits Rectangle {
    in property <string> text;
    in property <color> text-color: Colors.textBody;
    in property <bool> enabled <=> touch-area.enabled;
    out property <bool> has-focus: focus-scope.has-focus;
    in property <LayoutAlignment> alignment: center;

    padding-right: 12px;
    padding-left: 12px;
    padding-top: 4px;
    padding-bottom: 4px;

    callback clicked <=> touch-area.clicked;

    accessible-label: text;
    accessible-enabled: true;
    accessible-role: button;

    accessible-action-default() => {
        clicked()
    }

    forward-focus: focus-scope;

    HorizontalLayout {
        padding-right: root.padding-right;
        padding-left: root.padding-left;
        padding-top: root.padding-top;
        padding-bottom: root.padding-bottom;
        alignment: alignment;
        vertical-stretch: 0;
        cross-axis-alignment: center;

        Text {
            text: text;
            color: text-color;
        }
    }

    touch-area := TouchArea {
        width: parent.width;
        height: parent.height;
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                clicked();
                return accept;
            }
            return reject;
        }
    }

    if root.has-focus: FocusBorder {
        border-radius: root.border-radius;
    }
}

export enum PrimaryButtonTheme {
    accent,
    neutral,
    ghost
}

// TODO: test focus scope
export component PrimaryButton {
    in property <PrimaryButtonTheme> theme: accent;
    in property <string> text;
    callback clicked <=> button.clicked;

    function background-color(button-theme: PrimaryButtonTheme) -> color {
        if (button-theme == PrimaryButtonTheme.accent) {
            return Colors.accent;
        }
        if (button-theme == PrimaryButtonTheme.neutral) {
            return Colors.neutral50;
        }
        return transparent;
    }

    function text-color(button-theme: PrimaryButtonTheme) -> color {
        if (button-theme == PrimaryButtonTheme.accent) {
            return white;
        }
        return Colors.textBody;
    }

    button := Button {
        text: text;
        background: background-color(theme);
        text-color: text-color(theme);

        border-radius: 4px;
    }
}
