// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "../colors.slint";
import { FocusBorder } from "./focus-border.slint";
import { IconDisplay, IconSet, Icon } from "@lucide";

export component Button inherits Rectangle {
    in property <string> text;
    in property <color> background-color;
    in property <color> text-color: Colors.textBody;
    in property <color> hover-background-color;
    in property <bool> enabled: true;
    out property <bool> has-focus: focus-scope.has-focus;
    in property <LayoutAlignment> alignment: center;
    background: touch-area.has-hover ? hover-background-color : background-color;

    padding-right: 12px;
    padding-left: 12px;
    padding-top: 4px;
    padding-bottom: 4px;

    callback clicked <=> touch-area.clicked;

    accessible-label: text;
    accessible-enabled: enabled;
    accessible-role: button;

    animate background { duration: 150ms; }

    accessible-action-default() => {
        clicked();
    }

    forward-focus: focus-scope;

    touch-area := TouchArea {
        enabled: enabled;
    }

    HorizontalLayout {
        padding-right: root.padding-right;
        padding-left: root.padding-left;
        padding-top: root.padding-top;
        padding-bottom: root.padding-bottom;
        alignment: alignment;
        cross-axis-alignment: center;

        spacing: 4px;

        @children

        Text {
            text: text;
            color: text-color;
        }
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks

        key-pressed(event) => {
            if (event.text == Key.Space || event.text == Key.Return) {
                clicked();
                return accept;
            }
            return reject;
        }
    }

    if root.has-focus: FocusBorder {
        border-radius: root.border-radius;
    }
}

export enum IconButtonTheme {
    accent,
    neutral,
    ghost,
}

export component IconButton {
    in property <IconButtonTheme> theme: accent;
    in property <bool> enabled <=> touch-area.enabled;
    out property <bool> has-focus: focus-scope.has-focus;
    in property <Icon> icon;

    padding: 4px;

    callback clicked <=> touch-area.clicked;

    accessible-enabled: true;
    accessible-role: button;

    accessible-action-default() => {
        clicked()
    }

    function background-color(button-theme: IconButtonTheme) -> color {
        if (button-theme == IconButtonTheme.accent) {
            return Colors.accent;
        }
        if (button-theme == IconButtonTheme.neutral) {
            return Colors.neutral50;
        }
        return transparent;
    }

    function icon-color(button-theme: IconButtonTheme) -> color {
        if (button-theme == IconButtonTheme.accent) {
            return white;
        }
        return Colors.textBody;
    }

    forward-focus: focus-scope;

    background := Rectangle {
        background: background-color(theme);
        border-radius: 4px;
    }

    HorizontalLayout {
        padding: root.padding;

        IconDisplay {
            icon: root.icon;
            size: 14px;
            stroke-width: 2;
            stroke: icon-color(theme);
        }
    }

    touch-area := TouchArea {
        width: parent.width;
        height: parent.height;
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks

        key-pressed(event) => {
            if (event.text == Key.Space || event.text == Key.Return) {
                clicked();
                return accept;
            }
            return reject;
        }
    }

    if root.has-focus: FocusBorder {
        border-radius: background.border-radius;
    }
}

export enum PrimaryButtonTheme {
    accent,
    neutral,
    ghost,
}

export component PrimaryButton {
    in property <PrimaryButtonTheme> theme: accent;
    in property <string> text;
    callback clicked <=> button.clicked;

    function background-color(button-theme: PrimaryButtonTheme) -> color {
        if (button-theme == PrimaryButtonTheme.accent) {
            return Colors.accent;
        }
        if (button-theme == PrimaryButtonTheme.neutral) {
            return Colors.neutral50;
        }
        return transparent;
    }

    function hover-background-color(button-theme: PrimaryButtonTheme) -> color {
        if (button-theme == PrimaryButtonTheme.accent) {
            return Colors.accent.darker(0.2);
        }
        if (button-theme == PrimaryButtonTheme.neutral) {
            return Colors.neutral100;
        }
        return transparent;
    }

    function text-color(button-theme: PrimaryButtonTheme) -> color {
        if (button-theme == PrimaryButtonTheme.accent) {
            return white;
        }
        return Colors.textBody;
    }

    button := Button {
        text: text;
        background-color: background-color(theme);
        hover-background-color: hover-background-color(theme);
        text-color: text-color(theme);

        border-radius: 4px;
        @children
    }
}

export enum TextButtonTheme {
    accent,
    neutral,
}

export component TextButton {
    in property <TextButtonTheme> theme: accent;
    out property <color> text-color: text-color-impl(theme);
    in property <string> text;
    callback clicked <=> button.clicked;

    function hover-background-color(button-theme: TextButtonTheme) -> color {
        if (button-theme == TextButtonTheme.accent) {
            return Colors.accent.transparentize(0.9);
        }
        if (button-theme == TextButtonTheme.neutral) {
            return Colors.neutral100;
        }
        return transparent;
    }

    function text-color-impl(button-theme: TextButtonTheme) -> color {
        if (button-theme == TextButtonTheme.accent) {
            return Colors.accent;
        }
        return Colors.textBody;
    }

    button := Button {
        text: text;
        hover-background-color: hover-background-color(theme);
        text-color: text-color-impl(theme);

        border-radius: 4px;
        @children
    }
}
