// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "../colors.slint";
import { ListView, ScrollView } from "std-widgets.slint";
import { FocusBorder } from "./focus-border.slint";

export struct ComboBoxItem {
    value: string,
    text: string,
}

export component ComboBox {
    in property <[ComboBoxItem]> options;
    in-out property <int> current-index: 0;
    in-out property <string> current-value: options[current-index].value;
    in property <bool> enabled;

    callback changed(value: string);
    public function open() {
        popup.show();
    }

    public function select(index: int) {
        current-index = index;
    }

    public function move-selection-up() {
        root.select(Math.max(root.current-index - 1, 0));
    }

    public function move-selection-down() {
        root.select(Math.min(root.current-index + 1, root.options.length - 1));
    }

    accessible-role: combobox;
    accessible-enabled: enabled;
    accessible-expandable: true;
    accessible-value: current-value;
    forward-focus: focus-scope;

    focus-scope := FocusScope {
        enabled: root.enabled;
        key-pressed(event) => {
            if (!self.enabled) {
                return reject;
            }
            if (event.text == Key.Space || event.text == Key.Return) {
                return accept;
            }
            return reject;
        }

        touch-area := TouchArea {
            clicked => {
                popup.show();
            }
        }
    }

    background := Rectangle {
        background: white;
        //border-color: Colors.accent;
        border-width: 1px;
        border-radius: 4px;
        vertical-stretch: 1;
        clip: true;
    }

    HorizontalLayout {
        padding: 4px;
        text := Text {
            text: options[current-index].text;
            color: Colors.textBody;
            width: 100%;
            horizontal-alignment: left;
            vertical-alignment: center;
            overflow: elide;
            horizontal-stretch: 1;
            vertical-stretch: 1;
        }
    }

    popup := PopupWindow {
        width: max(root.width,250px);
        y: root.y + background.height;
        height: min(content.preferred-height,250px);
        close-policy: close-on-click-outside;
        forward-focus: popup-fs;

        popup-background := Rectangle {
            background: white;
            border-radius: 12px;
            border-width: 1px;
            border-color: Colors.neutral50;
        }

        popup-fs := FocusScope {
            key-pressed(event) => {
                if (!self.enabled) {
                    return reject;
                }
                if (event.text == Key.UpArrow) {
                    root.move-selection-up();
                    return accept;
                } else if (event.text == Key.DownArrow) {
                    root.move-selection-down();
                    return accept;
                } else if (event.text == Key.Return || event.text == Key.Escape) {
                    changed(options[current-index].value);
                    popup.close();
                    return accept;
                }
                return reject;
            }
        }

        flickable := Flickable {
            max-height: 250px;
            content-height: content.preferred-height;
            content := VerticalLayout {
                for option[i] in options: Rectangle {
                    background: current-index == i ? Colors.neutral50 : white;
                    height: 24px;

                    states [
                        hovered when inner-touch-area.has-hover: {
                            background: Colors.neutral50;
                            in {
                                animate background{
                                    duration: 150ms;
                                }
                            }
                        }
                    ]
                    inner-touch-area := TouchArea {
                        clicked => {
                            root.select(i);
                            changed(options[current-index].value);
                            popup.close();
                        }
                    }

                    Text {
                        text: option.text;
                        color: Colors.textBody;
                    }
                }
            }
        }
    }

    if focus-scope.has-focus: FocusBorder { }
}
