// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "../colors.slint";

export component ContextMenu inherits PopupWindow {
    close-policy: close-on-click-outside;

    Rectangle {
        width: context-menu-inner.preferred-width;
        height: context-menu-inner.preferred-height;
        background: white;
        border-radius: 4px;
        border-color: Colors.neutral50;
        border-width: 1px;

        context-menu-inner := VerticalLayout {
            cross-axis-alignment: start;
            padding: 4px;
            spacing: 4px;

            @children
        }
    }
}
