// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "../colors.slint";
import { Button } from "button.slint";

export component ContextMenuItem {
    in property <string> text;
    callback clicked <=> button.clicked;
    width: 100%;

    button := Button {
        width: 100%;
        text: text;
        hover-background-color: Colors.neutral50;
        border-radius: 4px;
        alignment: start;
        @children
    }
}

export component ContextMenu inherits PopupWindow {
    close-policy: close-on-click-outside;

    Rectangle {
        width: max(context-menu-inner.preferred-width,parent.width);
        height: max(context-menu-inner.preferred-height,parent.height);
        background: white;
        border-radius: 4px;
        border-color: Colors.neutral50;
        border-width: 1px;

        context-menu-inner := VerticalLayout {
            cross-axis-alignment: start;
            alignment: start;
            padding: 8px;
            spacing: 4px;

            @children
        }
    }
}
