// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "../colors.slint";
import { Button } from "button.slint";

export component ContextMenuItem {
    in property <string> text;
    callback clicked <=> button.clicked;
    width: 100%;

    button := Button {
        width: 100%;
        text: text;
        hover-background: Colors.neutral50;
        border-radius: 4px;
        alignment: start;
        @children
    }
}

export component ContextMenu inherits PopupWindow {
    close-policy: close-on-click-outside;

    Rectangle {
        width: max(context-menu-inner.preferred-width,parent.width);
        height: max(context-menu-inner.preferred-height,parent.height);
        background: white;
        border-radius: 4px;
        border-color: Colors.neutral50;
        border-width: 1px;

        context-menu-inner := VerticalLayout {
            cross-axis-alignment: start;
            alignment: start;
            padding: 8px;
            spacing: 4px;

            @children
        }
    }
}
