// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "../colors.slint";

export component ProgressBar {
    in-out property <float> progress;
    in property <color> track-color: Colors.neutral50;
    in property <color> thumb-color: green;

    Rectangle {
        width: 100%;
        height: 5px;
        border-radius: 999px;
        background: track-color;
        clip: true;

        Rectangle {
            x: parent.x;
            width: parent.width * progress;
            border-radius: 999px;
            background: thumb-color;
        }
    }
}
