// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "../colors.slint";

export component ProgressBar {
    in-out property <float> progress;
    in property <color> track-color: Colors.neutral50;
    in property <color> thumb-color: green;

    Rectangle {
        width: 100%;
        height: 5px;
        border-radius: 999px;
        background: track-color;
        clip: true;

        Rectangle {
            x: parent.x;
            width: parent.width * progress;
            border-radius: 999px;
            background: thumb-color;
        }
    }
}
