// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import { Colors } from "../colors.slint";

// TODO: handle cursor position and scrolling
export component TextField {
    in-out property <string> label;
    in property <string> placeholder-text;
    in-out property <string> text <=> text-input.text;
    in property <int> font-weight: FontWeight.normal;
    in-out property <InputType> input-type <=> text-input.input-type;
    in-out property <TextHorizontalAlignment> horizontal-alignment <=> text-input.horizontal-alignment;
    callback edited <=> text-input.edited;
    callback accepted <=> text-input.accepted;

    forward-focus: text-input;

    VerticalLayout {
        spacing: 8px;

        if label != "": Text {
            text: label;
            color: Colors.textBody;
        }

        Rectangle {
            background: white;
            border-color: text-input.has-focus ? Colors.accent : Colors.neutral50;
            border-width: 1px;
            border-radius: 4px;
            clip: true;

            VerticalLayout {
                padding-top: 4px;
                padding-bottom: 4px;
                padding-left: 8px;
                padding-right: 8px;

                text-input := TextInput {
                    font-weight: font-weight;
                    //accessible-placeholder-text: placeholder-text;
                    color: Colors.textBody;
                    text: placeholder-text;
                }
            }
        }
    }
}

export component InlineTextField {
    in property <string> text;
    in property <int> font-weight: FontWeight.normal;
    in property <string> field-text: text;
    property <bool> active: false;
    in property <InputType> input-type: InputType.text;
    callback accepted(string);

    Rectangle {
        TouchArea {
            clicked => {
                if (!active) {
                    active = true;
                }
            }
        }

        Text {
            visible: !active;
            text: text;
            font-weight: font-weight;
            color: Colors.textBody;
        }

        if active: TextField {
            text: field-text;
            input-type: input-type;
            font-weight: font-weight;
            init => {
                self.focus();
            }
            accepted => {
                accepted(self.text);
                active = false;
            }
        }
    }
}
