// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "../colors.slint";
import { ListView, ScrollView } from "std-widgets.slint";
import { FocusBorder } from "./focus-border.slint";

export struct ComboBoxItem {
    value: string,
    text: string,
}

export global ComboBoxApi {
    // Work around because Slint doesn't have any find-index like API.
    pure callback find-index(options: [ComboBoxItem], value: string) -> int;
}

export component ComboBox {
    in-out property <string> label;
    in property <[ComboBoxItem]> options;
    out property <int> current-index: 0;
    in-out property <string> current-value: options[current-index].value;
    in property <bool> enabled: true;

    callback changed(value: string);

    init => {
        current-index = ComboBoxApi.find-index(options, current-value);
    }

    public function open() {
        popup.show();
    }

    public function select(index: int) {
        current-index = index;
    }

    public function move-selection-up() {
        root.select(Math.max(root.current-index - 1, 0));
    }

    public function move-selection-down() {
        root.select(Math.min(root.current-index + 1, root.options.length - 1));
    }

    accessible-role: combobox;
    accessible-enabled: enabled;
    accessible-expanded: popup.is-open;
    accessible-expandable: true;
    accessible-value: current-value;
    forward-focus: focus-scope;

    focus-scope := FocusScope {
        enabled: root.enabled;
        key-pressed(event) => {
            if (!self.enabled) {
                return reject;
            }
            if (event.text == Key.Space || event.text == Key.Return) {
                return accept;
            }
            return reject;
        }

        touch-area := TouchArea {
            enabled: root.enabled;
            clicked => {
                popup.show();
            }
        }
    }

    layout := VerticalLayout {
        spacing: 8px;
        alignment: start;

        if label != "": Text {
            text: label;
            color: Colors.textBody;
        }

        Rectangle {
            background: white;
            border-color: Colors.neutral50;
            border-width: 1px;
            border-radius: 8px;
            clip: true;

            VerticalLayout {
                padding-top: 4px;
                padding-bottom: 4px;
                padding-left: 8px;
                padding-right: 8px;
                alignment: start;
                text := Text {
                    text: options[current-index].text;
                    color: Colors.textBody;
                    width: 100%;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    overflow: elide;
                    horizontal-stretch: 1;
                    vertical-stretch: 1;
                }
            }
        }
    }

    popup := PopupWindow {
        width: max(root.width,250px);
        y: layout.height + 8px;
        height: min(content.preferred-height,250px);
        close-policy: close-on-click-outside;
        forward-focus: popup-fs;

        popup-background := Rectangle {
            background: white;
            border-radius: 8px;
            border-width: 1px;
            border-color: Colors.neutral50;
        }

        popup-fs := FocusScope {
            key-pressed(event) => {
                if (!self.enabled) {
                    return reject;
                }
                if (event.text == Key.UpArrow) {
                    root.move-selection-up();
                    return accept;
                } else if (event.text == Key.DownArrow) {
                    root.move-selection-down();
                    return accept;
                } else if (event.text == Key.Return || event.text == Key.Escape) {
                    changed(options[current-index].value);
                    popup.close();
                    return accept;
                }
                return reject;
            }
        }

        flickable := Flickable {
            max-height: 250px;
            content-height: content.preferred-height;
            content := VerticalLayout {
                padding: 8px;
                spacing: 4px;

                for option[i] in options: Rectangle {
                    background: current-index == i ? Colors.neutral50 : white;
                    height: 24px;
                    border-radius: 4px;

                    states [
                        hovered when inner-touch-area.has-hover: {
                            background: Colors.neutral50;
                            in {
                                animate background { duration: 150ms; }
                            }
                        }
                    ]
                    inner-touch-area := TouchArea {
                        clicked => {
                            root.select(i);
                            changed(options[current-index].value);
                            popup.close();
                        }
                    }

                    Text {
                        text: option.text;
                        color: Colors.textBody;
                    }
                }
            }
        }
    }

    if focus-scope.has-focus: FocusBorder { }
}
