[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
rusqlite.workspace = true
clap.workspace = true
tracing-appender.workspace = true
mukwa-core = {path = "../core"}
usvg = "0.48.1"
ureq = "3.4.2"
zip = "8.6.0"
