// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import {
    StandardListView,
    VerticalBox,
    ListView,
    Palette,
    LineEdit,
} from "std-widgets.slint";
import { Colors } from "colors.slint";
import {
    Account,
    Transaction,
    State,
    Category,
    Api,
} from "globals.slint";
export {
    Account,
    Transaction,
    State,
    CreateTransactionOpts,
    Category,
    Api,
    CategoryGroup,
    AccountType,
}from "globals.slint";
export { Settings }from "settings.slint";
export { AnalyticsApi, PieChartSlice }from "analytics-page.slint";
import {
    Button,
    TextField,
    ComboBox,
    PrimaryButton,
    ContextMenu,
    ContextMenuItem,
} from "widgets.slint";
import { TransactionPage } from "transaction-page.slint";
import { SpendingPage } from "spending-page.slint";
import { ComboBoxItem } from "widgets/combobox.slint";
export { ComboBoxApi }from "widgets/combobox.slint";
export { Date, CalendarState }from "widgets/calendar.slint";
import { Table } from "tableview.slint";
import { IconDisplay, IconSet, Icon } from "@lucide";
import { SettingsDialog, Settings } from "settings.slint";
import { FontSize } from "theme.slint";
import { AnalyticsPage } from "analytics-page.slint";

enum Page {
    spending,
    transactions,
    analytics,
}

component SidebarButton inherits Button {
    in property <bool> selected;
    alignment: start;
    padding-top: 8px;
    padding-bottom: 8px;
    padding-left: 16px;
    padding-right: 16px;
    font-weight: FontWeight.medium;
    background: selected ? Colors.neutral50 : transparent;
    border-radius: 4px;

    @children
}

component AccountListItem inherits SidebarButton {
    in property <Account> account;
    in property <string> active-account-id;
    callback select-account(string);

    alignment: start;
    selected: active-account-id == account.id;

    clicked => select-account(account.id);
    right-clicked => context-menu.show();

    context-menu := ContextMenu {
        min-width: 250px;
        min-height: 50px;
        ContextMenuItem {
            text: @tr("Delete");
            clicked => {
                State.delete-account(account.id);
                parent.close();
            }
        }
    }

    HorizontalLayout {
        alignment: space-between;
        width: 100%;

        Text {
            text: account.name;
            color: Colors.textBody;
        }

        Text {
            text: State.format-money(account.balance, Settings.currency-code);
            color: Colors.textBody;
        }
    }
}

component AccountSection inherits VerticalLayout {
    in property <[Account]> accounts;
    in property <Page> current-page;
    in property <string> active-account-id;
    callback select-page(Page);
    callback select-account(string);

    SidebarButton {
        text: @tr("All accounts");
        selected: current-page == Page.transactions && active-account-id == "";
        clicked => select-page(Page.transactions);

        IconDisplay {
            icon: IconSet.PiggyBank;
            size: 14px;
            stroke-width: 1.5;
            stroke: Colors.textBody;
        }
    }

    Flickable {
        max-height: 250px;
        content-height: content.preferred-height;

        content := VerticalLayout {
            padding-left: 16px;

            for account in accounts: AccountListItem{
                account: account;
                active-account-id: active-account-id;
                select-account(account-id) => select-account(account-id);
            }
        }
    }
}

component CreateAccount inherits PopupWindow {
    x: Api.window-size().width * 0.5 - self.width * 0.5;
    y: Api.window-size().height * 0.5 - self.height * 0.5;
    width: 450px;
    close-policy: close-on-click-outside;

    function submit() {
        account-type.current-value == "cash"
            ? State.create-account(name.text,cash,balance.text)
            : State.create-account(name.text,credit,balance.text);
        self.close();
    }

    init => {
        name.focus();
    }

    Rectangle {
        background: white;
        border-radius: 24px;
        border-width: 1px;
        border-color: Colors.borderNeutral;
    }

    VerticalLayout {
        padding: 24px;
        spacing: 32px;

        Text {
            text: @tr("Create account");
            color: Colors.textHeading;
            font-size: FontSize.heading-sm;
        }

        VerticalLayout {
            spacing: 16px;
            name := TextField {
                label: @tr("Name");
                accepted => submit();
            }

            balance := TextField {
                label: @tr("Starting balance");
                input-type: decimal;
                accepted => submit();
            }

            account-type := ComboBox {
                label: @tr("Account type");
                options: [
                    { value: "cash", text:"Cash account" },
                    { value: "credit", text:"Credit account" },
                ];
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 12px;

            PrimaryButton {
                theme: neutral;
                text: @tr("Close");
                clicked => root.close();
            }

            PrimaryButton {
                text: @tr("Create account");
                clicked => submit();
            }
        }
    }
}

component Sidebar {
    in-out property <[Account]> accounts;
    in property <Page> current-page;
    in property <string> active-account-id;
    callback select-page(Page);
    callback select-account(string);
    width: 350px;

    accessible-role: navigation;

    background := Rectangle {
        background: Colors.neutral25;
    }

    create-account-dialog := CreateAccount { }

    HorizontalLayout {
        VerticalLayout {
            spacing: 16px;
            padding-right: 8px;
            padding-left: 8px;
            padding-top: 12px;
            padding-bottom: 12px;
            alignment: start;

            VerticalLayout {
                spacing: 4px;

                SidebarButton {
                    text: @tr("Spending");
                    selected: current-page == Page.spending && active-account-id == "";
                    clicked => select-page(Page.spending);
                    IconDisplay {
                        icon: IconSet.Banknote;
                        size: 14px;
                        stroke-width: 2;
                        stroke: Colors.textBody;
                    }
                }

                SidebarButton {
                    text: @tr("Analytics");
                    selected: current-page == Page.analytics && active-account-id == "";
                    clicked => select-page(Page.analytics);
                    IconDisplay {
                        icon: IconSet.ChartPie;
                        size: 14px;
                        stroke-width: 2;
                        stroke: Colors.textBody;
                    }
                }

                AccountSection {
                    current-page: current-page;
                    select-page(page) => select-page(page);
                    select-account(id) => select-account(id);
                    active-account-id: active-account-id;
                    accounts: accounts;
                }
            }

            VerticalLayout {
                spacing: 12px;
                padding-left: 4px;

                create-account-btn := PrimaryButton {
                    theme: neutral;
                    text: @tr("Create account");
                    clicked => create-account-dialog.show();
                }
            }

            Rectangle {
                vertical-stretch: 1;
            }

            SidebarButton {
                text: @tr("Settings");
                clicked => settings-dialog.show();

                IconDisplay {
                    icon: IconSet.Settings;
                    size: 13px;
                    stroke-width: 2;
                    stroke: Colors.textBody;
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Colors.neutral100;
        }
    }

    settings-dialog := SettingsDialog { }
}

export component MainWindow inherits Window {
    property <Page> active-page: Page.transactions;
    property <string> active-account-id;

    preferred-width: 750px;
    preferred-height: 750px;
    background: white;
    title: "Mukwa";
    icon: @image-url("../resources/icons/app-icon.png");
    default-font-family: Settings.font-family;
    default-font-size: FontSize.body;

    HorizontalLayout {
        Sidebar {
            accounts: State.accounts;
            current-page: active-page;
            active-account-id: active-account-id;
            select-page(page) => {
                active-page = page;
                active-account-id = "";
            }
            select-account(id) => {
                active-account-id = id;
                active-page = Page.transactions;
            }
        }

        if active-page == Page.spending: SpendingPage { }

        if active-page == Page.analytics: AnalyticsPage { }

        if active-page == Page.transactions: TransactionPage {
            active-account-id: active-account-id;
            transactions: State.transactions;
        }
    }
}
