// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "colors.slint";
import { Table, TableRow, TableCell } from "tableview.slint";
import { Api } from "globals.slint";
import { ComboBox, PrimaryButton, IconButton } from "widgets.slint";
import { ComboBoxItem } from "widgets/combobox.slint";
import { FontSize } from "theme.slint";
import { IconSet } from "@lucide";

export global ImportCsvState {
    callback import-transactions();
    callback read-csv(data-transfer);
    pure callback open-csv() -> data-transfer;
    pure callback csv-combobox-options([[string]]) -> [ComboBoxItem];

    in-out property <string> account-id;
    in-out property <[[string]]> records;
    in-out property <int> date-column-index;
    in-out property <int> payee-column-index;
    in-out property <int> note-column-index;
    in-out property <int> outflow-column-index;
    in-out property <int> inflow-column-index;

    public function set-records(data: [[string]]) {
        records = data;
        date-column-index = min(0,ImportCsvState.records[0].length);
        payee-column-index = min(1,ImportCsvState.records[0].length);
        note-column-index = min(2,ImportCsvState.records[0].length);
        outflow-column-index = min(3,ImportCsvState.records[0].length);
        inflow-column-index = min(4,ImportCsvState.records[0].length);
    }
}

export component ImportCsvDialog inherits PopupWindow {
    width: Api.window-size().width * 0.6;
    height: Api.window-size().height * 0.85;
    close-policy: close-on-click-outside;
    in property <data-transfer> data;
    in property <string> account-id;
    property <[string]> columns: [@tr("Date"), @tr("Note"), @tr("Outflow"), @tr("Inflow")];

    init => {
        ImportCsvState.read-csv(data);
        //ImportCsvState.set-records();
        ImportCsvState.account-id = account-id;
    }

    Rectangle {
        background: white;
        border-color: Colors.borderNeutral;
        border-width: 1px;
        border-radius: 24px;
    }

    VerticalLayout {
        padding: 36px;
        spacing: 20px;

        HorizontalLayout {
            cross-axis-alignment: center;
            alignment: space-between;

            Text {
                text: @tr("Import transactions");
                font-size: FontSize.body-lg;
                font-weight: FontWeight.semi-bold;
                color: Colors.textHeading;
            }

            IconButton {
                icon: IconSet.X;
                theme: ghost;
                clicked => root.close();
            }
        }

        // TODO: add none option
        HorizontalLayout {
            spacing: 16px;
            ComboBox {
                label: @tr("Date");
                current-value: ImportCsvState.records[0][ImportCsvState.date-column-index];
                options: ImportCsvState.csv-combobox-options(ImportCsvState.records);
                changed(value) => {
                     // TODO: use max here and test it?
                    ImportCsvState.date-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Note");
                current-value: ImportCsvState.records[0][ImportCsvState.note-column-index];
                options: ImportCsvState.csv-combobox-options(ImportCsvState.records);
                changed(value) => {
                    ImportCsvState.note-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Outflow");
                current-value: ImportCsvState.records[0][ImportCsvState.outflow-column-index];
                options: ImportCsvState.csv-combobox-options(ImportCsvState.records);
                changed(value) => {
                    ImportCsvState.outflow-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Inflow");
                current-value: ImportCsvState.records[0][ImportCsvState.inflow-column-index];
                options: ImportCsvState.csv-combobox-options(ImportCsvState.records);
                changed(value) => {
                    ImportCsvState.inflow-column-index = self.current-index
                }
            }
        }

        Table {
            property <int> length: 4;
            TableRow {
                for column in columns: TableCell {
                    width: parent.width / length;
                    Text {
                        text: column;
                        font-weight: FontWeight.semi-bold;
                        color: Colors.textBody;
                    }
                }
            }

            for record in ImportCsvState.records: TableRow {
                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[ImportCsvState.date-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[ImportCsvState.note-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[ImportCsvState.outflow-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[ImportCsvState.inflow-column-index];
                        color: Colors.textBody;
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: end;

            PrimaryButton {
                text: @tr("Cancel");
                theme: ghost;
                clicked => {
                    root.close();
                }
            }

            PrimaryButton {
                text: @tr("Import");
                clicked => {
                    ImportCsvState.import-transactions();
                    root.close();
                }
            }
        }
    }
}
