// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "colors.slint";
import { Table, TableRow, TableCell } from "tableview.slint";
import { Api } from "globals.slint";
import { ComboBox } from "widgets.slint";

export component ImportCsvDialog inherits PopupWindow {
    // FIXME: absolute position not working, based on parent
    x: Api.window-size().width * 0.5 - self.width * 0.5;
    y: Api.window-size().height * 0.5 - self.height * 0.5;
    width: Api.window-size().width * 0.80;
    height: Api.window-size().height * 0.85;
    close-policy: close-on-click-outside;
    in property <data-transfer> data;
    property <[[string]]> records;
    property <int> date-column-index: min(0,records[0].length);
    property <int> payee-column-index: min(1,records[0].length);
    property <int> category-column-index: min(2,records[0].length);
    property <int> note-column-index: min(3,records[0].length);
    property <int> outflow-column-index: min(4,records[0].length);
    property <int> inflow-column-index: min(5,records[0].length);
    property <[string]> columns: [
        @tr("Date"),
        @tr("Payee"),
        @tr("Category"),
        @tr("Note"),
        @tr("Outflow"),
        @tr("Inflow")
    ];

    init => {
        records = Api.read-csv(data);
    }

    Rectangle {
        background: white;
        border-color: Colors.borderNeutral;
        border-width: 1px;
        border-radius: 24px;
    }

    VerticalLayout {
        padding: 36px;

        // TODO: add none option
            HorizontalLayout {
            spacing: 16px;
            ComboBox {
                label: @tr("Date");
                current-value: records[0][date-column-index];
                options: Api.csv-combobox-options(records);
                changed(value) => {
                     // TODO: use max here and test it?
                    date-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Payee");
                current-value: records[0][payee-column-index];
                options: Api.csv-combobox-options(records);
                changed(value) => {
                    payee-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Category");
                current-value: records[0][category-column-index];
                options: Api.csv-combobox-options(records);
                changed(value) => {
                    category-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Note");
                current-value: records[0][note-column-index];
                options: Api.csv-combobox-options(records);
                changed(value) => {
                    note-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Outflow");
                current-value: records[0][outflow-column-index];
                options: Api.csv-combobox-options(records);
                changed(value) => {
                    outflow-column-index = self.current-index
                }
            }

            ComboBox {
                label: @tr("Inflow");
                current-value: records[0][inflow-column-index];
                options: Api.csv-combobox-options(records);
                changed(value) => {
                    inflow-column-index = self.current-index
                }
            }
        }

        Table {
            property <int> length: 6;
            TableRow {
                for column in columns: TableCell {
                    width: parent.width / length;
                    Text {
                        text: column;
                        font-weight: FontWeight.semi-bold;
                        color: Colors.textBody;
                    }
                }
            }

            for record in records: TableRow {
                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[date-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[payee-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[category-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[note-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[outflow-column-index];
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    width: parent.width / length;
                    Text {
                        text: record[inflow-column-index];
                        color: Colors.textBody;
                    }
                }
            }
        }
    }
}
