// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "colors.slint";
import { Date, CalendarState } from "widgets/calendar.slint";
import {
    State,
    Category,
    CategoryGroup,
    Budget,
    Api,
} from "globals.slint";
import {
    Button,
    TextField,
    PrimaryButton,
    IconButton,
    ProgressBar,
    InlineTextField,
    ContextMenu,
    ContextMenuItem,
} from "widgets.slint";
import { IconSet } from "@lucide";
import { Settings } from "settings.slint";
import { FontSize } from "theme.slint";

component CategoryItem inherits VerticalLayout {
    in property <Date> current-date;
    in property <Category> category;
    property <Budget> budget: State.get-budget(category.id, current-date);

    function budget-progress() -> float {
        if Api.money-to-float(budget.amount) <= 0 && Api.money-to-float(State.total-spent(budget.id)) > 0 {
            return 1;
        }
        if Api.money-to-float(budget.amount) <= 0 {
            return 0;
        }
        return Math.max(Api.money-to-float(State.total-spent(budget.id)))
            / Api.money-to-float(budget.amount);
    }

    // FIXME: category text field not working

    context-menu := ContextMenu {
        min-width: 250px;
        min-height: 50px;
        ContextMenuItem {
            text: @tr("Delete");
            clicked => {
                State.delete-category(category.id);
                parent.close();
            }
        }
    }

    DragArea {
        data: State.category-to-transfer(category.id);
        allow-move: true;

        TouchArea {
            pointer-event(event) => {
                if (event.button == PointerEventButton.right) {
                    context-menu.show();
                }
            }
        }

        HorizontalLayout {
            padding-left: 32px;
            padding-right: 16px;
            padding-top: 12px;
            padding-bottom: 12px;
            cross-axis-alignment: center;

            VerticalLayout {
                max-width: 500px;
                spacing: 12px;

                HorizontalLayout {
                    alignment: space-between;
                    cross-axis-alignment: center;

                    Rectangle {
                        width: 100px;
                        property <bool> active: false;

                        TouchArea {
                            clicked => {
                                if (!active) {
                                    active = true;
                                }
                            }
                        }

                        if active: TextField {
                            width: 100%;
                            text: category.title;

                            accepted => {
                                State.update-category(category.id, self.text);
                                active = false;
                            }
                        }

                        if !active: Text {
                            width: 100%;
                            text: category.title;
                            color: Colors.textBody;
                        }
                    }

                    Text {
                        text: "Spent "
                            + State.format-money(State.total-spent(budget.id),Settings.currency-code)
                            + " of "
                            + State.format-money(budget.amount,Settings.currency-code);
                        color: Colors.textBody;
                    }
                }

                ProgressBar {
                    progress: budget-progress();
                    thumb-color: budget-progress() > 1 ? Colors.red700 : green;
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            InlineTextField {
                text: State.format-money(budget.amount,Settings.currency-code);
                field-text: Api.format-money-without-symbol(budget.amount);
                input-type: decimal;
                accepted(value) => State.edit-budget(budget.id, value);
            }

            Text {
                width: 100px;
                text: State.format-money(State.total-spent(budget.id),Settings.currency-code);
                color: Colors.textBody;
                horizontal-alignment: end;
            }

            Text {
                width: 100px;
                text: State.format-money(State.left-to-spend(budget.id),Settings.currency-code);
                color: Colors.textBody;
                horizontal-alignment: end;
            }
        }
    }

    Rectangle {
        width: 100%;
        height: 1px;
        background: Colors.neutral50;
    }
}

component CategoryGroupItem {
    in property <Date> current-date;
    in property <CategoryGroup> category-group;
    property <bool> open: true;

    drop-area := DropArea {
        can-drop(event) => event.proposed-action;
        dropped(event) => {
            State.move-category(State.transfer-to-category(event.data), category-group.id);
            return event.proposed-action;
        }
    }

    context-menu := ContextMenu {
        min-width: 250px;
        min-height: 50px;
        ContextMenuItem {
            text: @tr("Delete");
            clicked => {
                State.delete-category-group(category-group.id);
                parent.close();
            }
        }
    }

    TouchArea {
        pointer-event(event) => {
            if (event.button == PointerEventButton.right) {
                context-menu.show();
            }
        }
    }

    Rectangle {
        states [
            drag-over when drop-area.has-drag: {
                background: Colors.neutral50;
                in {
                    animate background { duration: 150ms; }
                }
            }
        ]
    }

    VerticalLayout {
        category-popup := PopupWindow {
            width: 250px;
            x: category-button.x;
            y: popup-position-y();
            height: layout.preferred-height;

            function popup-position-y() -> length {
                if (category-button.absolute-position.y > Api.window-size().height * 0.5) {
                    return category-button.y - self.height;
                }
                return category-button.y + category-button.height + 4px;
            }

            init => {
                if (self.y > Api.window-size().height * 0.5) {
                    self.y = category-button.y - self.width
                }
            }

            close-policy: close-on-click-outside;

            Rectangle {
                background: white;
                border-width: 1px;
                border-radius: 4px;
                border-color: Colors.neutral50;
            }

            layout := VerticalLayout {
                alignment: start;
                padding: 8px;
                spacing: 12px;

                text-field := TextField {
                    placeholder-text: @tr("New category");
                    accepted => {
                        State.create-category(self.text,category-group.id);
                        category-popup.close();
                    }
                }

                HorizontalLayout {
                    spacing: 8px;
                    cross-axis-alignment: start;

                    PrimaryButton {
                        theme: ghost;
                        text: @tr("Cancel");
                        clicked => category-popup.close();
                    }

                    PrimaryButton {
                        text: @tr("Confirm");
                        clicked => {
                            State.create-category(text-field.text,category-group.id);
                            category-popup.close();
                        }
                    }
                }
            }
        }

        Rectangle {
            background: Colors.neutral25;
            HorizontalLayout {
                padding-left: 8px;
                padding-right: 16px;
                padding-top: 4px;
                padding-bottom: 4px;

                cross-axis-alignment: center;

                IconButton {
                    icon: IconSet.ChevronDown;
                    theme: ghost;
                    states [
                        closed when !root.open: {
                            transform-rotation: -90deg;
                            in-out {
                                animate transform-rotation { duration: 150ms; }
                            }
                        }
                    ]
                    clicked => {
                        root.open = !open;
                    }
                }

                InlineTextField {
                    text: category-group.title;
                    font-weight: FontWeight.semi-bold;
                    accepted(value) => State.update-category-group(category-group.id, value);
                }

                category-button := IconButton {
                    icon: IconSet.Plus;
                    theme: ghost;
                    clicked => {
                        category-popup.show();
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                Text {
                    width: 100px;
                    text: State.format-money(State.total-assigned-in-group(category-group.id,current-date),Settings.currency-code);
                    color: Colors.textBody;
                    horizontal-alignment: end;
                }

                Text {
                    width: 100px;
                    text: State.format-money(State.total-spent-in-group(category-group.id, current-date),Settings.currency-code);
                    color: Colors.textBody;
                    horizontal-alignment: end;
                }

                Text {
                    width: 100px;
                    text: State.format-money(State.left-to-spend-in-group(category-group.id,current-date),Settings.currency-code);
                    color: Colors.textBody;
                    horizontal-alignment: end;
                }
            }
        }

        if root.open: VerticalLayout {
            for category in State.categories-in-group(category-group.id): CategoryItem {
                current-date: current-date;
                category: category;
            }
        }
    }
}

export component SpendingPage inherits VerticalLayout {
    in-out property <Date> current-date: CalendarState.today();
    alignment: start;
    spacing: 12px;

    HorizontalLayout {
        spacing: 4px;
        cross-axis-alignment: center;
        alignment: start;
        padding: 16px;

        IconButton {
            icon: IconSet.ChevronLeft;
            theme: ghost;
            accessible-label: @tr("Previous month");
            clicked => {
                current-date = CalendarState.decrement-month(current-date);
                State.set-current-budget-month(current-date);
            }
        }

        Text {
            font-size: FontSize.heading-sm;
            color: Colors.textHeading;
            text: State.format-dateym(current-date);
        }

        IconButton {
            icon: IconSet.ChevronRight;
            theme: ghost;
            accessible-label: @tr("Next month");
            clicked => {
                current-date = CalendarState.increment-month(current-date);
                State.set-current-budget-month(current-date);
            }
        }
    }

    HorizontalLayout {
        alignment: start;
        padding-left: 16px;
        padding-right: 16px;
        button := PrimaryButton {
            text: @tr("New category group");
            clicked => {
                popup.show();
            }
        }
    }

    popup := PopupWindow {
        width: 250px;
        x: button.x;
        y: button.y + button.height + 4px;
        height: layout.preferred-height;
        close-policy: close-on-click-outside;

        Rectangle {
            background: white;
            border-width: 1px;
            border-radius: 4px;
            border-color: Colors.neutral50;
        }

        layout := VerticalLayout {
            alignment: start;
            padding: 8px;
            spacing: 12px;

            text-field := TextField {
                placeholder-text: @tr("New category group");
                accepted => {
                    State.create-category-group(self.text);
                    popup.close();
                }
            }

            HorizontalLayout {
                spacing: 8px;
                cross-axis-alignment: start;

                PrimaryButton {
                    theme: ghost;
                    text: @tr("Cancel");
                    clicked => popup.close();
                }

                PrimaryButton {
                    text: @tr("Confirm");
                    clicked => {
                        State.create-category-group(text-field.text);
                        popup.close();
                    }
                }
            }
        }
    }

    VerticalLayout {
        HorizontalLayout {
            padding-left: 16px;
            padding-right: 16px;
            padding-bottom: 8px;
            padding-top: 8px;

            Text {
                text: @tr("Category");
                font-weight: FontWeight.semi-bold;
                color: Colors.textBody;
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            Text {
                width: 100px;
                text: @tr("Assigned");
                font-weight: FontWeight.semi-bold;
                horizontal-alignment: end;
                color: Colors.textBody;
            }

            Text {
                width: 100px;
                font-weight: FontWeight.semi-bold;
                text: @tr("Spent");
                horizontal-alignment: end;
                color: Colors.textBody;
            }

            Text {
                width: 100px;
                font-weight: FontWeight.semi-bold;
                text: @tr("Available");
                horizontal-alignment: end;
                color: Colors.textBody;
            }
        }

        Flickable {
            content-height: content.preferred-height;

            content := VerticalLayout {
                for category-group in State.category-groups: CategoryGroupItem {
                    category-group: category-group;
                    current-date: current-date;
                }
            }
        }
    }
}
