#!/usr/bin/env bash

#TODO: compile for ARM
#wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage

cargo build -r --target x86_64-unknown-linux-gnu
#cargo build -r --target aarch64--unknown-linux-gnu

./bin/linuxdeploy-x86_64.AppImage \
    --appdir build/AppDir \
    -e target/x86_64-unknown-linux-gnu/release/mukwa \
    -d resources/mukwa.desktop \
    --output appimage \
    -i resources/icons/app-icon.svg

#./bin/linuxdeploy-x86_64.AppImage \
#    --appdir build/AppDir \
#    -e target/release/aarch64-unknown-linux-gnu/mukwa \
#    -d resources/mukwa.desktop \
#    --output appimage \
#    -i resources/icons/app-icon.svg