// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "colors.slint";

export component AnalyticsPage {
    HorizontalLayout {
        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
        }
    }

    Image {
        //source: @image-url("image.png");
    }
}
