// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "colors.slint";
import { FontSize } from "theme.slint";
import { State } from "globals.slint";
import { Settings } from "settings.slint";

export struct PieChartSlice {
    fill: color,
    arc-path: string,
    line-path: string,
}

export global AnalyticsApi {
    pure callback draw-pie-chart(width: length, height: length) -> [PieChartSlice];
}

export component AnalyticsPage inherits VerticalLayout {
    padding: 24px;
    spacing: 24px;

    Text {
        text: @tr("Spending chart");
        color: Colors.textHeading;
        font-size: FontSize.heading-sm;
    }

    VerticalLayout {
        spacing: 36px;
        VerticalLayout {
            spacing: 8px;
            alignment: start;
            Text {
                text: @tr("Total spent");
                color: Colors.textBody;
                font-weight: FontWeight.medium;
            }

            Text {
                text: State.format-money(State.total-spent-all(), Settings.currency-code);
                color: Colors.textHeading;
                font-size: FontSize.heading-sm;
                font-weight: FontWeight.medium;
            }
        }

        Rectangle {
            width: 500px;
            height: 500px;
            for slice in AnalyticsApi.draw-pie-chart(self.width, self.height): Rectangle {
                Path {
                    width: 100%;
                    height: 100%;
                    viewbox-width: 500;
                    viewbox-height: 500;
                    fill: slice.fill;
                    commands: slice.arc-path;
                }

                Path {
                    width: 100%;
                    height: 100%;
                    viewbox-width: 500;
                    viewbox-height: 500;
                    stroke: Colors.neutral200;
                    commands: slice.line-path;
                }
            }
        }
    }
}
