// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "colors.slint";

// TODO: show info on hover
// TODO: maybe grid
component Bar {
    in property <string> day;
    width: 100%;

    HorizontalLayout {
        width: 100%;
        spacing: 8px;
        cross-axis-alignment: center;

        // Text {
        //     text: day;
        //     color: Colors.textMuted;
        // }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.accent;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }

        Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }
    }
}

export component AnalyticsPage inherits VerticalLayout {
    width: 100%;
    height: 100%;
    property <[bool]> days: [
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
    ];

    Rectangle {
        width: 50px;
        height: 50px;
        background: Colors.blue100;
    }

    GridLayout {
        spacing: 8px;
        for day in days: Rectangle {
            width: 20px;
            height: 20px;
            background: Colors.neutral50;
            border-radius: 4px;
        }
    }

    VerticalLayout {
        width: 100%;
        spacing: 8px;
        Bar {
            day: @tr("Sun");
        }

        Bar {
            day: @tr("Mon");
        }

        Bar {
            day: @tr("Tue");
        }

        Bar {
            day: @tr("Wed");
        }

        Bar {
            day: @tr("Thu");
        }

        Bar {
            day: @tr("Fri");
        }

        Bar {
            day: @tr("Sat");
        }
    }
}
