// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import {
    StandardListView,
    VerticalBox,
    ListView,
    Palette,
    LineEdit,
} from "std-widgets.slint";
import { Colors } from "./colors.slint";
import { Account, Transaction, State, Category } from "./globals.slint";
export { Account, Transaction, State, Category } from "./globals.slint";
import { Button, TextField } from "./widgets.slint";
import { TransactionPage } from "./transaction.slint";
import { SpendingPage } from "spending-page.slint";
import { PrimaryButton } from "widgets/button.slint";
import { ComboBoxItem } from "widgets/combobox.slint";
export { Date, CalendarState } from "./widgets/calendar.slint";
import { Table } from "tableview.slint";
import { TransactionPage } from "transaction.slint";
import { IconDisplay, IconSet, Icon } from "@lucide";

enum Page {
    spending,
    transactions
}

component SidebarButton inherits Button {
    in property <bool> selected;
    alignment: start;
    padding-top: 8px;
    padding-bottom: 8px;
    padding-left: 16px;
    padding-right: 16px;

    background: selected ? Colors.neutral50 : transparent;
    border-radius: 4px;

    @children
}

component Sidebar {
    in-out property <[Account]> accounts;
    in property <Page> current-page;
    callback select-page(Page);
    width: 350px;

    accessible-role: navigation;

    background := Rectangle {
        background: Colors.neutral25;
    }

    HorizontalLayout {
        VerticalLayout {
            spacing: 16px;
            padding-right: 8px;
            padding-left: 8px;
            padding-top: 12px;
            padding-bottom: 12px;
            alignment: start;

            VerticalLayout {
                spacing: 4px;
                SidebarButton {
                    text: @tr("Spending");
                    selected: current-page == Page.spending;
                    clicked => select-page(Page.spending);
                    IconDisplay {
                        icon: IconSet.Banknote;
                        size: 14px;
                        stroke-width: 2;
                        stroke: Colors.textBody;
                    }
                }

                SidebarButton {
                    text: @tr("All accounts");
                    selected: current-page == Page.transactions;
                    clicked => select-page(Page.transactions);

                    IconDisplay {
                        icon: IconSet.PiggyBank;
                        size: 14px;
                        stroke-width: 1.5;
                        stroke: Colors.textBody;
                    }
                }
            }

            VerticalLayout {
                spacing: 12px;
                padding-left: 4px;
                HorizontalLayout {
                    alignment: space-between;
                    Text {
                        text: @tr("Accounts");
                        color: black;
                        font-weight: 600;
                    }

                    Text {
                        text: State.total_balance();
                        color: black;
                        font-weight: 600;
                    }
                }

                VerticalLayout {
                    Flickable {
                        max-height: 250px;
                        viewport-height: content.preferred-height;

                        // TODO: use dialog for creating account
                        // TODO: context menu with rename that opens a popup
                        content := VerticalLayout {
                            for account in accounts: HorizontalLayout {
                                spacing: 12px;
                                alignment: space-between;
                                Text {
                                    text: account.name;
                                    color: black;
                                }

                                Text {
                                    text: State.account-balance(account.id);
                                    color: Colors.textBody;
                                }
                            }
                        }
                    }
                }

                PrimaryButton {
                    theme: neutral;
                    text: @tr("Create account");
                    clicked => State.create_account("New account");
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Colors.neutral100;
        }
    }
}

export component MainWindow inherits Window {
    property <Page> active-page: Page.transactions;
    preferred-width: 750px;
    preferred-height: 750px;
    background: white;
    title: "Mukwa";

    HorizontalLayout {
        Sidebar {
            accounts: State.accounts;
            current-page: active-page;
            select-page(page) => {
                active-page = page;
            }
        }

        if active-page == Page.spending: SpendingPage { }

        if active-page == Page.transactions: TransactionPage {
            columns: [@tr("Date"), @tr("Account"), @tr("Category"), @tr("Outflow"), @tr("Inflow")];
            transactions: State.transactions;
        }
    }
}
