// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import {
    StandardListView,
    VerticalBox,
    ListView,
    Palette,
    LineEdit,
} from "std-widgets.slint";
import { Colors } from "colors.slint";
import {
    Account,
    Transaction,
    State,
    Category,
    Api,
} from "globals.slint";
export {
    Account,
    Transaction,
    State,
    CreateTransactionOpts,
    Category,
    Api,
    CategoryGroup,
}from "globals.slint";
export { Settings }from "settings.slint";
import { Button, TextField } from "widgets.slint";
import { TransactionPage } from "transaction-page.slint";
import { SpendingPage } from "spending-page.slint";
import { PrimaryButton } from "widgets/button.slint";
import { ComboBoxItem } from "widgets/combobox.slint";
export { Date, CalendarState }from "widgets/calendar.slint";
import { Table } from "tableview.slint";
import { IconDisplay, IconSet, Icon } from "@lucide";
import { SettingsDialog, Settings } from "settings.slint";

enum Page { spending, transactions }

component SidebarButton inherits Button {
    in property <bool> selected;
    alignment: start;
    padding-top: 8px;
    padding-bottom: 8px;
    padding-left: 16px;
    padding-right: 16px;

    background-color: selected ? Colors.neutral50 : transparent;
    border-radius: 4px;
    hover-background-color: Colors.neutral50;

    @children
}

component AccountSection inherits VerticalLayout {
    in property <[Account]> accounts;
    in property <Page> current-page;
    in property <string> active-account-id;
    callback select-page(Page);
    callback select-account(string);

    SidebarButton {
        text: @tr("All accounts");
        selected: current-page == Page.transactions && active-account-id == "";
        clicked => select-page(Page.transactions);

        IconDisplay {
            icon: IconSet.PiggyBank;
            size: 14px;
            stroke-width: 1.5;
            stroke: Colors.textBody;
        }
    }

    Flickable {
        max-height: 250px;
        content-height: content.preferred-height;

        content := VerticalLayout {
            padding-left: 16px;

            for account in accounts: SidebarButton {
                alignment: start;
                selected: active-account-id == account.id;
                clicked => select-account(account.id);
                HorizontalLayout {
                    alignment: space-between;
                    width: 100%;

                    Text {
                        text: account.name;
                        color: Colors.textBody;
                    }

                    Text {
                        text: State.format-money(State.account-balance(account.id), Settings.currency-code);
                        color: Colors.textBody;
                    }
                }
            }
        }
    }
}

component Sidebar {
    in-out property <[Account]> accounts;
    in property <Page> current-page;
    in property <string> active-account-id;
    callback select-page(Page);
    callback select-account(string);
    width: 350px;

    accessible-role: navigation;

    background := Rectangle {
        background: Colors.neutral25;
    }

    HorizontalLayout {
        VerticalLayout {
            spacing: 16px;
            padding-right: 8px;
            padding-left: 8px;
            padding-top: 12px;
            padding-bottom: 12px;
            alignment: start;

            VerticalLayout {
                spacing: 4px;

                SidebarButton {
                    text: @tr("Spending");
                    selected: current-page == Page.spending && active-account-id == "";
                    clicked => select-page(Page.spending);
                    IconDisplay {
                        icon: IconSet.Banknote;
                        size: 14px;
                        stroke-width: 2;
                        stroke: Colors.textBody;
                    }
                }

                AccountSection {
                    current-page: current-page;
                    select-page(page) => select-page(page);
                    select-account(id) => select-account(id);
                    active-account-id: active-account-id;
                    accounts: accounts;
                }
            }

            VerticalLayout {
                spacing: 12px;
                padding-left: 4px;

                create-account-btn := PrimaryButton {
                    theme: neutral;
                    text: @tr("Create account");
                    clicked => popup.show();
                }

                popup := PopupWindow {
                    width: create-account-btn.width;
                    x: create-account-btn.x;
                    y: create-account-btn.y + create-account-btn.height + 4px;
                    height: layout.preferred-height;

                    close-policy: close-on-click-outside;

                    forward-focus: focus-scope;
                    focus-scope := FocusScope {
                        key-pressed(event) => {
                            if (event.text == Key.Return) {
                                State.create-account(text-field.text);
                                popup.close();
                                return accept;
                            }
                            if (event.text == Key.Escape) {
                                popup.close();
                                return accept;
                            }
                            return reject;
                        }
                    }

                    Rectangle {
                        background: white;
                        border-width: 1px;
                        border-radius: 4px;
                        border-color: Colors.neutral50;
                    }

                    layout := VerticalLayout {
                        alignment: start;
                        padding: 8px;
                        spacing: 12px;

                        Text {
                            text: @tr("Create new account");
                            font-size: 13px;
                            font-weight: 500;
                            color: Colors.textHeading;
                        }

                        VerticalLayout {
                            spacing: 4px;

                            Text {
                                text: @tr("Account name");
                                color: Colors.textBody;
                            }

                            text-field := TextField {
                                placeholder-text: @tr("My account");
                                accepted => {
                                    State.create-account(text-field.text);
                                    popup.close();
                                }
                            }
                        }

                        HorizontalLayout {
                            spacing: 8px;
                            cross-axis-alignment: start;

                            PrimaryButton {
                                theme: ghost;
                                text: @tr("Cancel");
                                clicked => popup.close();
                            }

                            PrimaryButton {
                                text: @tr("Create");
                                clicked => {
                                    State.create-account(text-field.text);
                                    popup.close();
                                }
                            }
                        }
                    }
                }
            }

            Rectangle {
                vertical-stretch: 1;
            }

            SidebarButton {
                text: @tr("Settings");
                clicked => settings-dialog.show();

                IconDisplay {
                    icon: IconSet.Settings;
                    size: 13px;
                    stroke-width: 2;
                    stroke: Colors.textBody;
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Colors.neutral100;
        }
    }

    settings-dialog := SettingsDialog { }
}

export component MainWindow inherits Window {
    property <Page> active-page: Page.transactions;
    property <string> active-account-id;

    preferred-width: 750px;
    preferred-height: 750px;
    background: white;
    title: "Mukwa";
    default-font-family: Settings.font-family;

    HorizontalLayout {
        Sidebar {
            accounts: State.accounts;
            current-page: active-page;
            active-account-id: active-account-id;
            select-page(page) => {
                active-page = page;
                active-account-id = "";
            }
            select-account(id) => {
                active-account-id = id;
                active-page = Page.transactions;
            }
        }

        if active-page == Page.spending: SpendingPage { }

        if active-page == Page.transactions: TransactionPage {
            active-account-id: active-account-id;
            transactions: State.transactions;
        }
    }
}
