import {
    StandardListView,
    VerticalBox,
    ListView,
    Palette,
} from "std-widgets.slint";
import { Colors } from "./colors.slint";
import { Account, Transaction, State } from "./globals.slint";
import { Sidebar } from "./sidebar.slint";
export { Account, Transaction, State } from "./globals.slint";
import { Button } from "./widgets.slint";
import { TransactionTable } from "./transaction.slint";
export { Date, CalendarState } from "./widgets/calendar.slint";

export component MainWindow inherits Window {
    preferred-width: 750px;
    preferred-height: 750px;
    background: white;
    title: "Mukwa";

    HorizontalLayout {
        Sidebar {
            accounts: State.accounts;
        }

        TransactionTable {
            columns: [@tr("Date"), @tr("Account"), @tr("Category"), @tr("Outflow"), @tr("Inflow")];
            transactions: State.transactions;
        }
    }
}
