export global Colors {
    // Raw color values
    out property <color> blue50: #e5f2ff;
    out property <color> blue100: #cee9ff;
    out property <color> blue200: #95d3ff;
    out property <color> blue300: #32bfff;
    out property <color> blue400: #03a5e0;
    out property <color> blue500: #0088b9;
    out property <color> blue600: #006b92;
    out property <color> blue700: #015170;
    out property <color> blue800: #00374d;
    out property <color> blue900: #002030;
    out property <color> blue950: #00131e;

    out property <color> green50: #ebffe9;
    out property <color> green100: #c8ffc4;
    out property <color> green200: #8efe80;
    out property <color> green300: #4ff720;
    out property <color> green400: #49e71c;
    out property <color> green500: #44d81a;
    out property <color> green600: #33a913;
    out property <color> green700: #247e0a;
    out property <color> green800: #155504;
    out property <color> green900: #072d01;
    out property <color> green950: #031d01;

    out property <color> neutral100: #e6e6e6;
    out property <color> neutral200: #cbcbcb;
    out property <color> neutral25: #fcfcfc;
    out property <color> neutral300: #bebebe;
    out property <color> neutral400: #9e9e9e;
    out property <color> neutral50: #f7f7f7;
    out property <color> neutral500: #808080;
    out property <color> neutral600: #787878;
    out property <color> neutral700: #626262;
    out property <color> neutral800: #3e3e3e;
    out property <color> neutral900: #282828;
    out property <color> neutral950: #171717;

    out property <color> purple50: #eeecfd;
    out property <color> purple100: #e0dcfb;
    out property <color> purple200: #c3b9f8;
    out property <color> purple300: #a796f4;
    out property <color> purple400: #896fef;
    out property <color> purple500: #7048e9;
    out property <color> purple600: #5b28d4;
    out property <color> purple700: #471ea9;
    out property <color> purple800: #31137a;
    out property <color> purple900: #1d084f;
    out property <color> purple950: #110434;

    out property <color> red50: #feeded;
    out property <color> red100: #fedada;
    out property <color> red200: #fdb4b4;
    out property <color> red300: #fc8a8b;
    out property <color> red400: #fb5758;
    out property <color> red500: #ec181c;
    out property <color> red600: #bd1013;
    out property <color> red700: #910b0c;
    out property <color> red800: #670406;
    out property <color> red900: #400202;
    out property <color> red950: #2c0101;

    // Semantic colors
    out property <color> surfaceError: red500;
    out property <color> surfaceErrorActive: red700;
    out property <color> surfaceErrorHover: red600;

    out property <color> surfacePrimary: purple500;
    out property <color> surfacePrimaryActive: purple700;
    out property <color> surfacePrimaryHover: purple600;

    out property <color> textBody: neutral900;
    out property <color> textError: red400;
    out property <color> textHeading: neutral950;
    out property <color> textMuted: neutral600;
    out property <color> textPrimary: surfacePrimary;

    out property <color> borderNeutral10: neutral50;
    out property <color> borderNeutralFocus: purple500;
}
