// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

export struct Account {
    id: string,
    name: string,
    balance: string,
}

export enum TransactionType {
    income,
    expense,
    transfer
}

export struct Transaction {
    id: string,
    date: string,
    account-id: string,
    category-id: string,
    transaction-type: TransactionType,
    outflow: string,
    inflow: string,
}

export struct TransactionOption {
    value: string,
    text: string,
}

export struct UpdateTransactionOpts {
    id: string,
    account-id: string,
    outflow: string,
    inflow: string,
    date: string,
}

export global State {
    callback create_account(name: string);
    callback create_transaction();
    callback duplicate_transaction(id: string);
    callback delete_transaction(id: string);
    pure callback get_account_name(id: string) -> string;
    pure callback total_balance() -> string;
    pure callback get_category_name(id: string) -> string;
    pure callback update_transaction(id: string, account-id: string, outflow: string, inflow: string, date: string);
    in-out property <[Transaction]> transactions;
    // Account options for combo boxes
    in-out property <[{ value: string, text: string}]> account-options;
    in-out property <[Account]> accounts;
}
