// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { ComboBoxItem } from "widgets/combobox.slint";
import { Date } from "widgets/calendar.slint";

export enum AccountType {
    cash,
    credit,
}

export struct Account {
    id: string,
    name: string,
    account-type: AccountType,
}

export struct Category {
    id: string,
    title: string,
    group-id: string,
}

export struct CategoryGroup {
    id: string,
    title: string,
}

export struct Budget {
    id: string,
    category-id: string,
    amount: string,
    year: int,
    month: int,
}

export enum TransactionType { income, expense, transfer }

export struct Transaction {
    id: string,
    date: string,
    account-id: string,
    payee-id: string,
    category-id: string,
    transaction-type: TransactionType,
    outflow: string,
    note: string,
    inflow: string,
}

export struct TransactionOption {
    value: string,
    text: string,
}

export struct CreateTransactionOpts {
    account-id: string,
    category-id: string,
    payee-id: string,
    outflow: string,
    inflow: string,
    date: string,
    note: string,
}

export global Api {
    pure callback window-position() -> { x: length, y: length };
    pure callback window-size() -> { width: length, height: length };
    pure callback parse-date(string) -> Date;
    pure callback money-to-float(string) -> float;
    pure callback today() -> string;
    pure callback format-money-without-symbol(value: string) -> string;
}

export global State {
    callback create-account(name: string, type: AccountType);
    callback create-transaction(CreateTransactionOpts);
    callback duplicate-transaction(id: string);
    callback delete-transaction(id: string);
    callback delete-category(id: string);
    callback delete-category-group(id: string);
    callback edit-budget(id: string, amount: string);
    callback set-current-budget-month(Date);
    callback set-transaction-date(id: string, date: string);
    callback set-transaction-account(id: string, account-id: string);
    callback set-transaction-payee(id: string, account-id: string);
    callback set-transaction-note(id: string, note: string);
    callback set-transaction-category(id: string, category-id: string);
    callback set-transaction-outflow(id: string, amount: string);
    callback set-transaction-inflow(id: string, amount: string);
    callback update-category(id: string, title: string);
    callback update-category-group(id: string, title: string);
    callback create-category(title: string, group-id: string);
    callback move-category(id: string, group-id: string);
    callback create-category-group(title: string);

    pure callback category-to-transfer(id: string) -> data-transfer;
    pure callback transfer-to-category(data-transfer) -> string;
    pure callback total-balance() -> string;
    pure callback get-category(id: string) -> Category;
    pure callback get-account(id: string) -> Account;
    pure callback get-budget(category-id: string, month: Date) -> Budget;
    pure callback categories-in-group(id: string) -> [Category];
    pure callback account-balance(id: string) -> string;

    // Returns the year and month as a formatted string
    pure callback format-dateym(Date) -> string;
    pure callback format-date(string) -> string;
    pure callback format-money(value: string, currency-code: string) -> string;

    pure callback total-spent(budget-id: string) -> string;
    pure callback left-to-spend(id: string) -> string;
    pure callback total-spent-in-group(id: string, date: Date) -> string;
    pure callback total-assigned-in-group(id: string, date: Date) -> string;
    pure callback left-to-spend-in-group(id: string, date: Date) -> string;

    in-out property <[Transaction]> transactions;
    in-out property <[Category]> categories;
    in-out property <[CategoryGroup]> category-groups;
    in-out property <[Budget]> budgets;
    // Account options for combo boxes
    in-out property <[ComboBoxItem]> account-options;
    // Category options for combo boxes
    in-out property <[ComboBoxItem]> category-options;
    // All the supported currencies
    in-out property <[ComboBoxItem]> currency-options;
    // All the system fonts (that we found)
    in-out property <[ComboBoxItem]> font-options;
    in-out property <[Account]> accounts;
}
