// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Api } from "globals.slint";
import { ComboBox } from "widgets/combobox.slint";
import { Colors } from "colors.slint";
import { FontSize } from "theme.slint";
import { IconButton } from "widgets/button.slint";
import { IconSet } from "@lucide";
import { Table, TableRow, TableCell } from "tableview.slint";
import { PrimaryButton } from "widgets.slint";

export global ImportCsvState { }

// TODO: add no column option as -1
export component ImportCsvDialog inherits PopupWindow {
    // FIXME: absolute position not working, based on parent
    x: Api.window-size().width * 0.5 - self.width * 0.5;
    y: Api.window-size().height * 0.5 - self.height * 0.5;
    width: Api.window-size().width * 0.80;
    height: Api.window-size().height * 0.85;
    close-policy: close-on-click-outside;
    in property <data-transfer> data;
    property <[[string]]> records;
    property <int> date-column-index: min(0,records[0].length);
    property <int> payee-column-index: min(1,records[0].length);
    property <int> category-column-index: min(2,records[0].length);
    property <int> note-column-index: min(3,records[0].length);
    property <int> outflow-column-index: min(4,records[0].length);
    property <int> inflow-column-index: min(5,records[0].length);

    init => {
        records = Api.read-csv(data);
    }

    Rectangle {
        background: white;
        border-radius: 20px;
        border-color: Colors.neutral50;
        border-width: 1px;
    }

    VerticalLayout {
        spacing: 20px;
        padding: 36px;

        HorizontalLayout {
            alignment: space-between;
            Text {
                text: @tr("Import transactions");
                color: Colors.textHeading;
                font-size: FontSize.heading-sm;
            }

            IconButton {
                icon: IconSet.X;
                theme: ghost;
                clicked => root.close();
            }
        }

        VerticalLayout {
            alignment: start;
            HorizontalLayout {
                spacing: 16px;
                ComboBox {
                    label: @tr("Date");
                    current-value: records[0][date-column-index];
                    options: Api.csv-combobox-options(records);
                }

                ComboBox {
                    label: @tr("Payee");
                    current-value: records[0][payee-column-index];
                    options: Api.csv-combobox-options(records);
                }

                ComboBox {
                    label: @tr("Category");
                    current-value: records[0][category-column-index];
                    options: Api.csv-combobox-options(records);
                }

                ComboBox {
                    label: @tr("Note");
                    current-value: records[0][note-column-index];
                    options: Api.csv-combobox-options(records);
                }

                ComboBox {
                    label: @tr("Outflow");
                    current-value: records[0][outflow-column-index];
                    options: Api.csv-combobox-options(records);
                }

                ComboBox {
                    label: @tr("Inflow");
                    current-value: records[0][inflow-column-index];
                    options: Api.csv-combobox-options(records);
                }
            }
        }

        Table {
            TableRow {
                TableCell {
                    Text {
                        text: @tr("Date");
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    Text {
                        text: @tr("Payee");
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    Text {
                        text: @tr("Category");
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    Text {
                        text: @tr("Note");
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    Text {
                        text: @tr("Outflow");
                        color: Colors.textBody;
                    }
                }

                TableCell {
                    Text {
                        text: @tr("Inflow");
                        color: Colors.textBody;
                    }
                }
            }

            for record in records: TableRow {
                for cell in record: TableCell {
                    Text {
                        text: cell;
                        color: Colors.textBody;
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 16px;
            PrimaryButton {
                text: @tr("Cancel");
                theme: neutral;
            }

            PrimaryButton {
                text: @tr("Import");
            }
        }
    }
}
