// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import { Colors } from "colors.slint";

export global Settings {
    callback set-currency-code(string);
    in-out property <string> currency-code;
}
// TODO: sections
// - General
// - Appearance

export component SettingsDialog inherits PopupWindow {
    x: 0;
    y: 0;
    width: 600px;
    height: 600px;

    Rectangle {
        background: white;
    }

    HorizontalLayout {
        Rectangle {
            max-width: 250px;
            background: Colors.neutral25;
            VerticalLayout {
                padding-right: 8px;
                padding-left: 8px;
                padding-top: 12px;
                padding-bottom: 12px;
                spacing: 8px;
                Text {
                    text: "General";
                    color: Colors.textBody;
                }
            }
        }

        // TODO: dividers
        // TODO: Section component
        VerticalLayout {
            padding: 12px;
            alignment: start;
            spacing: 12px;
            Text {
                text: "General";
                font-size: 15px;
                color: Colors.textBody;
            }

            HorizontalLayout {
                alignment: space-between;
                cross-axis-alignment: center;
                Text {
                    text: "Currency";
                    color: Colors.textBody;
                }

                Text {
                    text: "CAD";
                    color: Colors.textBody;
                }
            }
        }
    }
}
