// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import {
    VerticalBox,
    LineEdit,
} from "std-widgets.slint";
import { Colors } from "./colors.slint";
import { Account, Transaction, State, Category } from "./globals.slint";
export { Account, Transaction, State } from "./globals.slint";
import { Button, TextField } from "./widgets.slint";
import { TransactionTable } from "./transaction.slint";
export { Date, CalendarState } from "./widgets/calendar.slint";


// TODO: add category groups
// TODO: add month switcher

export component SpendingPage inherits VerticalLayout {
    alignment: start;
    spacing: 12px;

    // TODO: add icon button
    // TODO: maybe ActionButton and base Button with all styles
    button := Button {
        text: "New category";
        clicked => {
            popup.show();
        }
    }

    // TODO: use list view
    // TODO: add focus-scope
    // TODO: maybe just make component
    popup := PopupWindow {
        width: 250px;
        x: button.x;
        y: button.y + button.height + 4px;
        height: layout.preferred-height;

        close-policy: close-on-click-outside;

        // TODO: add box shadow xs with just a border color
        Rectangle {
            background: white;
            border-width: 1px;
            border-radius: 4px;
            border-color: Colors.neutral50;
        }

        layout := VerticalLayout {
            alignment: start;
            padding: 8px;
            spacing: 12px;

            text-field := TextField {
                placeholder-text: "New category";
            }

            // TODO: submit on enter
            HorizontalLayout {
                spacing: 8px;
                cross-axis-alignment: start;

                Button {
                    text: "Cancel";
                    clicked => popup.close();
                }

                Button {
                    text: "Confirm";
                    clicked => {
                        State.create-category(text-field.text);
                        popup.close();
                    }
                }
            }
        }
    }

    // TODO: use scroll view
    // TODO: add Notion-like icon on the left side
    VerticalLayout {
        alignment: start;
        spacing: 8px;

        HorizontalLayout {
            alignment: space-between;
            Text {
                text: "Category";
                color: Colors.textBody;
            }

            Text {
                text: "Amount";
                color: Colors.textBody;
            }
        }

        for budget in State.budgets: HorizontalLayout {
            property <Category> category: State.get-category(budget.category-id);
            alignment: space-between;
            Text {
                text: category.title;
                color: Colors.textBody;
            }

            Text {
                text: budget.amount;
                color: Colors.textBody;
            }
        }
    }
}
