// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import {
    VerticalBox,
    LineEdit,
} from "std-widgets.slint";
import { Colors } from "./colors.slint";
import { Account, Transaction, State, Category, Budget } from "globals.slint";
import { Button, TextField, PrimaryButton } from "widgets.slint";


// TODO: add category groups
// TODO: add month switcher
// TODO: try Drag inside ListView

component BudgetItem {
    in property <Budget> budget;
    property <Category> category: State.get-category(budget.category-id);

    HorizontalLayout {
        Text {
            text: category.title;
            color: Colors.textBody;
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        Text {
            width: 100px;
            text: State.format-money(budget.amount);
            color: Colors.textBody;
            horizontal-alignment: end;
        }

        Text {
            width: 100px;
            text: State.format-money(State.total-spent(budget.id));
            color: Colors.textBody;
            horizontal-alignment: end;
        }

        Text {
            width: 100px;
            text: State.format-money(budget.amount);
            color: Colors.textBody;
            horizontal-alignment: end;
        }
    }
}

export component SpendingPage inherits VerticalLayout {
    alignment: start;
    spacing: 12px;
    padding: 16px;

    // TODO: add icon button
    button := PrimaryButton {
        text: "New category";
        clicked => {
            popup.show();
        }
    }

    // TODO: use list view
    // TODO: add focus-scope
    // TODO: maybe just make component
    popup := PopupWindow {
        width: 250px;
        x: button.x;
        y: button.y + button.height + 4px;
        height: layout.preferred-height;

        close-policy: close-on-click-outside;

        // TODO: add box shadow xs with just a border color
        Rectangle {
            background: white;
            border-width: 1px;
            border-radius: 4px;
            border-color: Colors.neutral50;
        }

        layout := VerticalLayout {
            alignment: start;
            padding: 8px;
            spacing: 12px;

            text-field := TextField {
                placeholder-text: "New category";
            }

            // TODO: submit on enter
            HorizontalLayout {
                spacing: 8px;
                cross-axis-alignment: start;

                PrimaryButton {
                    theme: ghost;
                    text: @tr("Cancel");
                    clicked => popup.close();
                }

                PrimaryButton {
                    text: @tr("Confirm");
                    clicked => {
                        State.create-category(text-field.text);
                        popup.close();
                    }
                }
            }
        }
    }

    // TODO: use scroll view
    // TODO: add Notion-like icon on the left side
    VerticalLayout {
        alignment: start;
        spacing: 8px;

        HorizontalLayout {
            // alignment: space-between;
            padding-bottom: 8px;
            padding-top: 8px;

            Text {
                text: @tr("Category");
                color: Colors.textBody;
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            Text {
                width: 100px;
                text: @tr("Assigned");
                horizontal-alignment: end;
                color: Colors.textBody;
            }

            Text {
                width: 100px;
                text: @tr("Spent");
                horizontal-alignment: end;
                color: Colors.textBody;
            }

            Text {
                width: 100px;
                text: @tr("Available");
                horizontal-alignment: end;
                color: Colors.textBody;
            }
        }

        for budget in State.budgets: BudgetItem {
            budget: budget;
        }
    }
}
