// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "colors.slint";
import { Button } from "widgets/button.slint";
import { ListView, ScrollView } from "std-widgets.slint";
import { PrimaryButton } from "widgets.slint";

export component TableCell inherits Rectangle {
    clip: true;
    in-out property <bool> is-editing;
    callback confirmed();
    callback cancelled();
    callback clicked();
    callback right-clicked();

    // TODO: add focus-scope
    // TODO: pass focus onto child
    touch-area := TouchArea {
        clicked => {
            is-editing = true;
            clicked();
        }
        pointer-event(event) => {
            if (event.button == PointerEventButton.right) {
                //right-clicked();
            }
        }
    }

    HorizontalLayout {
        alignment: start;
        @children
    }
}

export component TableRow {
    in-out property <bool> is-editing;
    callback confirmed();
    callback cancelled();
    callback clicked();
    callback right-clicked();

    touch-area := TouchArea {
        clicked => {
            clicked();
        }
        pointer-event(event) => {
            if (event.button == PointerEventButton.right) {
                right-clicked();
            }
        }
    }

    Rectangle {
        states [
            active when is-editing: {
                background: Colors.accent.with-alpha(0.1);
                in {
                    animate background { duration: 50ms; }
                }
                out {
                    animate background { duration: 50ms; }
                }
            }
            hovered when touch-area.has-hover: {
                background: Colors.neutral25;
                in {
                    animate background { duration: 50ms; }
                }
                out {
                    animate background { duration: 50ms; }
                }
            }
        ]
    }

    layout := VerticalLayout {
        HorizontalLayout {
            padding-left: root.padding-left;
            padding-right: root.padding-right;
            padding-top: 8px;
            padding-bottom: 8px;
            @children
        }

        if is-editing: HorizontalLayout {
            alignment: end;
            padding-bottom: 4px;
            padding-right: root.padding-right;
            spacing: 8px;

            cancel-btn := PrimaryButton {
                theme: ghost;
                text: @tr("Cancel");
                clicked => cancelled();
            }

            confirm-btn := PrimaryButton {
                text: @tr("Confirm");
                clicked => confirmed();
            }
        }

        Rectangle {
            width: 100%;
            height: 2px;
            background: Colors.neutral50;
        }
    }
}

export component Table {
    accessible-role: table;

    Flickable {
        content-height: layout.preferred-height;
        layout := VerticalLayout {
            @children
        }
    }

    // Flickable {
    //     height: 250px;
    //     layout := VerticalLayout {
    //         alignment: start;
    //         width: root.width;
    //         @children
    //     }
    // }
}
