// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Colors } from "colors.slint";
import { Button } from "widgets/button.slint";
import { ListView, ScrollView } from "std-widgets.slint";
import { PrimaryButton } from "widgets.slint";

export component TableCell inherits Rectangle {
    clip: true;
    in-out property <bool> is-editing;
    callback confirmed();
    callback cancelled();
    callback clicked();
    callback right-clicked();

    // TODO: add focus-scope
    // TODO: pass focus onto child
    touch-area := TouchArea {
        clicked => {
            is-editing = true;
            clicked();
        }
        pointer-event(event) => {
            if (event.button == PointerEventButton.right) {
                //right-clicked();
            }
        }
    }

    HorizontalLayout {
        alignment: start;
        @children
    }
}

export component TableRow {
    in-out property <bool> is-editing;
    callback confirmed();
    callback cancelled();
    callback clicked();
    callback right-clicked();

    touch-area := TouchArea {
        clicked => {
            clicked();
        }
        pointer-event(event) => {
            if (event.button == PointerEventButton.right) {
                right-clicked();
            }
        }
    }

    Rectangle {
        states [
            active when is-editing: {
                background: Colors.accent.with-alpha(0.1);
                in {
                    animate background { duration: 50ms; }
                }
                out {
                    animate background { duration: 50ms; }
                }
            }
            hovered when touch-area.has-hover: {
                background: Colors.neutral25;
                in {
                    animate background { duration: 50ms; }
                }
                out {
                    animate background { duration: 50ms; }
                }
            }
        ]
    }

    layout := VerticalLayout {
        padding-left: root.padding-left;
        padding-right: root.padding-right;

        HorizontalLayout {
            padding-top: 8px;
            padding-bottom: 8px;
            @children
        }

        if is-editing: HorizontalLayout {
            alignment: end;
            padding-bottom: 4px;
            spacing: 8px;

            cancel-btn := PrimaryButton {
                theme: ghost;
                text: @tr("Cancel");
                clicked => cancelled();
            }

            confirm-btn := PrimaryButton {
                text: @tr("Confirm");
                clicked => confirmed();
            }
        }

        Rectangle {
            width: 100%;
            height: 2px;
            background: Colors.neutral50;
        }
    }
}

export component Table {
    accessible-role: table;
    ScrollView {
        layout := VerticalLayout {
            alignment: start;
            width: root.width;
            @children
        }
    }
}
