// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// TODO: move to widgets
import { Colors } from "colors.slint";
import { Button } from "widgets/button.slint";
import { ListView, ScrollView } from "std-widgets.slint";

export component TableCell inherits Rectangle {
    clip: true;

    HorizontalLayout {
        alignment: start;
        @children
    }
}

// TODO: maybe optional actions?
export component TableRow {
    VerticalLayout {
        layout := HorizontalLayout {
            padding-top: 8px;
            padding-bottom: 8px;
            @children
        }

        Rectangle {
            width: 100%;
            height: 2px;
            background: Colors.neutral50;
        }
    }
}

export component Table {
    ScrollView {
        layout := VerticalLayout {
            width: root.width;
            @children
        }
    }
}
