// Mukwa - Personal finance
// Copyright (C) 2026  Wakunguma Kalimukwa
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import {
    StandardListView,
    VerticalBox,
    ListView,
    Palette,
    LineEdit,
} from "std-widgets.slint";
import { Colors } from "colors.slint";
import {
    Account,
    Transaction,
    State,
    UpdateTransactionOpts,
} from "globals.slint";
import { Button, ComboBox } from "widgets.slint";
import { FocusBorder } from "widgets/focus-border.slint";
import { Calendar } from "widgets/calendar.slint";
import { PrimaryButton } from "widgets/button.slint";
import { Table, TableRow, TableCell } from "tableview.slint";

// TODO: maybe enter should submit?
component EditingRow inherits VerticalLayout {
    in property <Transaction> transaction;
    out property <string> selected-account-id: transaction.account-id;
    out property <string> category-id: transaction.category-id;
    out property <string> outflow: transaction.outflow;
    out property <string> inflow: transaction.inflow;
    out property <string> selected-date: transaction.date;
    out property <UpdateTransactionOpts> update-opts;
    callback cancel();
    callback confirm();

    padding: 8px;
    spacing: 8px;

    HorizontalLayout {
        vertical-stretch: 0;
        cross-axis-alignment: center;

        touch-area := TouchArea {
            Text {
                horizontal-stretch: 1;
                horizontal-alignment: start;
                text: selected-date;
                color: Colors.textBody;
            }

            clicked => {
                calendar-popup.show();
            }
        }

        calendar-popup := PopupWindow {
            x: touch-area.x;
            y: touch-area.y;

            width: 250px;
            height: 250px;

            close-policy: close-on-click-outside;

            calendar := Calendar {
                changed(date) => {
                    selected-date = date.year + "-" + date.month + "-" + date.day;
                    calendar-popup.close();
                }
            }
        }

        ComboBox {
            options: State.account-options;
            changed(value) => {
                selected-account-id = value;
            }
        }

        ComboBox {
            options: State.category-options;
            changed(value) => {
                category-id = value;
            }
        }

        Rectangle {
            border-width: 1px;
            border-color: Colors.blue500;
            clip: true;
            width: 250px;
            height: 36px;
            border-radius: 4px;
            background: white;

            outflow-input := TextInput {
                text: outflow;
                color: Colors.textBody;
                input-type: decimal;
                edited => {
                    outflow = outflow-input.text;
                    inflow = "";
                    inflow-input.text = "";
                }
            }
        }

        Rectangle {
            border-width: 1px;
            border-color: Colors.blue500;
            clip: true;
            width: 250px;
            height: 36px;
            border-radius: 4px;
            background: white;

            inflow-input := TextInput {
                text: inflow;
                color: Colors.textBody;
                input-type: decimal;

                edited => {
                    inflow = inflow-input.text;
                    outflow = "";
                    outflow-input.text = "";
                }
            }
        }
    }

    HorizontalLayout {
        alignment: end;
        spacing: 8px;

        PrimaryButton {
            theme: ghost;
            text: "Cancel";
            clicked => cancel();
        }

        PrimaryButton {
            text: "Confirm";
            clicked => confirm();
        }
    }
}

component TransactionRow inherits Rectangle {
    in-out property <bool> is-active;
    in property <Transaction> transaction;
    in property <int> index;
    callback select-row(int);

    forward-focus: focus-scope;
    height: is-active ? edit-row.preferred-height : row.preferred-height;

    focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.Space) {
                select-row(index);
                return accept;
            }
            if (event.text == Key.Escape) {
                select-row(-1);
                return accept;
            }
            return reject;
        }
        touch-area := TouchArea {
            clicked => {
                if (!is-active) {
                    select-row(index);
                }
            }
        }
    }

    states [
        active when is-active: {
            background: Colors.blue50;
            in {
                animate background { duration: 50ms; }
            }
            out {
                animate background { duration: 50ms; }
            }
        }
        hovered when touch-area.has-hover: {
            background: Colors.neutral25;
            in {
                animate background { duration: 50ms; }
            }
            out {
                animate background { duration: 50ms; }
            }
        }
    ]

    ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("Duplicate");
                activated => State.duplicate_transaction(transaction.id);
            }

            MenuItem {
                title: @tr("Delete");
                activated => State.delete_transaction(transaction.id);
            }
        }
    }

    row := HorizontalLayout {
        padding-top: 8px;
        padding-bottom: 8px;
        visible: !is-active;
        cross-axis-alignment: center;

        Rectangle {
//            horizontal-stretch: 1;
            Text {
                width: 100%;
                horizontal-alignment: start;
                text: transaction.date;
                color: Colors.textBody;
            }

            background: Colors.blue50;
        }

        Rectangle {
//            horizontal-stretch: 1;
            Text {
                width: 100%;
                horizontal-alignment: start;
                text: State.get_account_name(transaction.account-id);
                color: Colors.textBody;
            }

            background: Colors.neutral50;
        }

        Rectangle {
//            horizontal-stretch: 1;
            Text {
                width: 100%;
                horizontal-alignment: start;
                text: State.get-category(transaction.category-id).title;
                color: Colors.textBody;
            }
        }

        Rectangle {
//            horizontal-stretch: 1;
            Text {
                width: 100%;
                horizontal-alignment: start;
                text: transaction.outflow;
                color: Colors.textBody;
            }
        }

        Rectangle {
//            horizontal-stretch: 1;
            Text {
                width: 100%;
                horizontal-alignment: start;
                text: transaction.inflow;
                color: Colors.textBody;
            }
        }
    }

    edit-row := EditingRow {
        visible: is-active;
        transaction: transaction;
        confirm => {
            // TODO: use struct
            State.update-transaction(transaction.id, edit-row.selected-account-id,edit-row.category-id, edit-row.outflow,edit-row.inflow,edit-row.selected-date);
            select-row(-1);
        }
        cancel => {
            select-row(-1);
        }
    }
}

component NewTransactionRow inherits TableRow {
    in property <Transaction> transaction;
    in property <int> length;
    // TODO: reset properties on cancel or click
    out property <string> category-id: transaction.category-id;
    out property <string> account-id: transaction.account-id;
    out property <string> outflow: transaction.outflow;
    out property <string> inflow: transaction.inflow;
    out property <string> date: transaction.date;

    date-cell := TableCell {
        width: parent.width / length;
        if !parent.is-editing: Text {
            text: transaction.date;
            color: Colors.textBody;
        }

        if parent.is-editing: touch-area := TouchArea {
            Text {
                horizontal-stretch: 1;
                horizontal-alignment: start;
                text: date;
                color: Colors.textBody;
            }

            clicked => {
                calendar-popup.show();
            }
        }

        calendar-popup := PopupWindow {
            x: date-cell.x;
            y: date-cell.y;

            width: 250px;
            height: 250px;

            close-policy: close-on-click-outside;

            calendar := Calendar {
                changed(value) => {
                    date = value.year + "-" + value.month + "-" + value.day;
                    calendar-popup.close();
                }
            }
        }
    }

    TableCell {
        width: parent.width / length;
        if !parent.is-editing: Text {
            text: State.get_account_name(transaction.account-id);
            color: Colors.textBody;
        }

        if parent.is-editing: ComboBox {
            options: State.account-options;
            changed(value) => {
                account-id = value;
            }
        }
    }

    TableCell {
        width: parent.width / length;
        if !parent.is-editing: Text {
            text: State.get-category(transaction.category-id).title;
            color: Colors.textBody;
        }

        if parent.is-editing: ComboBox {
            options: State.category-options;
            changed(value) => {
                category-id = value;
            }
        }
    }

    TableCell {
        width: parent.width / length;
        if !parent.is-editing: Text {
            text: transaction.outflow;
            color: Colors.textBody;
        }

        if parent.is-editing: Rectangle {
            border-width: 1px;
            border-color: Colors.blue500;
            clip: true;
            width: 250px;
            height: 36px;
            border-radius: 4px;
            background: white;

            outflow-input := TextInput {
                text: outflow;
                color: Colors.textBody;
                input-type: decimal;
                edited => {
                    outflow = outflow-input.text;
                    inflow = "";
                    // FIXME
                    //inflow-input.text = "";
                }
            }
        }
    }

    // TODO: use TextField
    TableCell {
        width: parent.width / length;
        if !parent.is-editing: Text {
            text: transaction.inflow;
            color: Colors.textBody;
        }

        if parent.is-editing: Rectangle {
            border-width: 1px;
            border-color: Colors.blue500;
            clip: true;
            width: 250px;
            height: 36px;
            border-radius: 4px;
            background: white;

            inflow-input := TextInput {
                text: inflow;
                color: Colors.textBody;
                input-type: decimal;

                edited => {
                    inflow = inflow-input.text;
                    outflow = "";
                    // FIXME
                    //outflow-input.text = "";
                }
            }
        }
    }
}

// TODO: add focus scope, and make sure it continues from the current index
export component TransactionTable inherits VerticalLayout {
    in property <[string]> columns;
    in property <[Transaction]> transactions;
    property <int> active-row: -1;

    function select-row(index: int) {
        active-row = index;
    }

    VerticalLayout {
        padding: 12px;
        spacing: 12px;

        Text {
            text: @tr("All accounts");
            font-size: 1.5rem;
            font-weight: 500;
            color: Colors.textHeading;
        }

        Text {
            text: State.total_balance();
            font-size: 1.25rem;
            color: Colors.textHeading;
        }
    }

    HorizontalLayout {
        alignment: end;
        padding-left: 16px;
        padding-right: 16px;
        padding-top: 8px;
        padding-bottom: 8px;

        PrimaryButton {
            text: @tr("Add transaction");
            clicked => State.create_transaction();
        }
    }

    // TODO: reset values after editing
    Table {
        width: 100%;
        property <int> length: 5;

        TableRow {
            for column in columns: TableCell {
                width: parent.width / length;
                Text {
                    text: column;
                    color: Colors.textBody;
                }
            }
        }

        for transaction[index] in transactions: NewTransactionRow {
            is-editing: active-row == index;
            transaction: transaction;
            length: length;
            clicked => {
                select-row(index);
            }
            cancelled => {
                select-row(-1);
            }
            confirmed => {
                select-row(-1);
            }
        }
    }

    //    VerticalLayout {
//        HorizontalLayout {
//            for column in columns: Rectangle {
//                Text {
//                    width: 100%;
//                    horizontal-alignment: start;
//                    text: column;
//                    color: Colors.textBody;
//                }
//            }
//        }
//
//        Rectangle {
//            width: 100%;
//            height: 2px;
//            background: Colors.neutral50;
//        }
//        // TODO: focus when clicked
//        // - Use accessibilty
//        ListView {
//            for transaction[i] in transactions: VerticalLayout {
//                TransactionRow {
//                    is-active: active-row == i;
//                    transaction: transaction;
//                    index: i;
//                    select-row(index) => {
//                        select-row(index)
//                    }
//                }
//
//                Rectangle {
//                    width: 100%;
//                    height: 2px;
//                    background: Colors.neutral50;
//                }
//            }
//        }
//    }
}
