// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Wakunguma Kalimukwa

import { Colors } from "../../colors.slint";
import {
    Transaction,
    State,
    Api,
} from "../../globals.slint";
import { FontSize } from "../../theme.slint";
import {
    ComboBox,
    ComboBoxItem,
    TextField,
    PrimaryButton,
    ContextMenu,
    ContextMenuItem,
    IconButton,
} from "../../widgets.slint";
import { Calendar, Date } from "../../widgets/calendar.slint";
import { Table, TableRow, TableCell } from "../../widgets/tableview.slint";
import { Settings } from "../../settings.slint";
import { IconSet, IconDisplay } from "@lucide";
import { ImportCsvDialog, ImportCsvState } from "import-csv.slint";

component ConfirmButton {
    in property <Transaction> transaction;

    popup := PopupWindow {
        x: icon-btn.width + 4px;
        close-policy: close-on-click-outside;
        Rectangle {
            background: white;
            border-color: Colors.borderNeutral;
            border-width: 1px;
            border-radius: 8px;
        }

        VerticalLayout {
            spacing: 8px;
            padding: 4px;

            PrimaryButton {
                theme: ghost;
                text: @tr("Confirm transaction");
                clicked => {
                    State.confirm-transaction(transaction.id);
                    popup.close();
                }
            }

            PrimaryButton {
                text: @tr("Reject transaction");
                theme: ghost;
                clicked => {
                    State.delete-transaction(transaction.id);
                    popup.close();
                }
            }
        }
    }

    icon-btn := IconButton {
        icon: IconSet.Info;
        theme: ghost;
        clicked => {
            popup.show();
        }
    }
}

component DateCell inherits TableCell {
    in property <Transaction> transaction;
    property <bool> is-unconfirmed: State.is-transaction-unconfirmed(transaction.id);
    callback changed(Date);

    clicked => {
        calendar-popup.show();
    }

    HorizontalLayout {
        spacing: 8px;
        if is-unconfirmed: ConfirmButton {
            transaction: transaction;
        }

        if !is-unconfirmed: Rectangle {
            width: 20px;
            height: 20px;
        }

        Text {
            text: State.format-date(transaction.date);
            color: Colors.textBody;
        }
    }

    calendar-popup := PopupWindow {
        x: 0;
        y: popup-position-y();

        width: calendar.preferred-width;
        height: calendar.preferred-height;
        close-policy: close-on-click-outside;

        function popup-position-y() -> length {
            if (root.absolute-position.y > Api.window-size().height * 0.5) {
                return -100px;
            }
            return root.height;
        }

        calendar := Calendar {
            x: parent.x;
            y: parent.y;
            date: Api.parse-date(transaction.date);
            changed(value) => {
                root.changed(value);
                calendar-popup.close();
            }
        }
    }
}

export component AccountCell inherits TableCell {
    in property <Transaction> transaction;
    in property <[ComboBoxItem]> options;
    in property <string> current-value;

    callback changed(string);

    if !self.is-editing: Text {
        text: State.get-account(transaction.account-id).name;
        color: Colors.textBody;
    }

    if self.is-editing: ComboBox {
        width: 100%;
        options: options;
        current-value: current-value;
        init => {
            self.open();
        }
        changed(value) => {
            root.changed(value);
            parent.is-editing = false;
        }
    }
}

component PayeeCell inherits TableCell {
    in property <Transaction> transaction;
    in property <string> active-account-id;

    function payee() -> string {
        if active-account-id.is-empty && transaction.transaction-type == transfer {
            return "Transfer:" + State.get-account(transaction.payee-id).name;
        }
        if active-account-id.is-empty {
            return "";
        }
        if active-account-id == transaction.payee-id {
            return "Transfer:" + State.get-account(transaction.account-id).name;
        }
        if active-account-id == transaction.account-id && transaction.transaction-type == transfer {
            return "Transfer:" + State.get-account(transaction.payee-id).name;
        }
        return State.get-account(transaction.payee-id).name;
    }

    callback changed(string);

    if !self.is-editing: Text {
        text: payee();
        color: Colors.textBody;
    }

    if self.is-editing: ComboBox {
        width: 100%;
        options: State.account-options;
        current-value: transaction.account-id;
        init => {
            self.open();
        }
        changed(value) => {
            root.changed(value);
            parent.is-editing = false;
        }
    }
}

component CategoryCell inherits TableCell {
    in property <Transaction> transaction;
    callback changed(string);

    if !self.is-editing: Text {
        text: State.get-category(transaction.category-id).title;
        color: Colors.textBody;
    }

    if self.is-editing: ComboBox {
        width: 100%;
        options: State.category-options;
        init => {
            self.open();
        }
        changed(value) => {
            parent.changed(value);
            parent.is-editing = false;
        }
    }
}

component NoteCell inherits TableCell {
    in property <Transaction> transaction;
    callback changed(string);

    if !self.is-editing: Text {
        text: transaction.note;
        color: Colors.textBody;
    }

    if self.is-editing: TextField {
        width: 100%;
        text: transaction.note;
        init => {
            self.focus();
        }
        accepted => {
            parent.changed(self.text);
            parent.is-editing = false;
        }
    }
}

component MoneyCell inherits TableCell {
    in property <string> amount;
    callback changed(string);

    if !self.is-editing: Text {
        text: State.format-money(amount,Settings.currency-code);
        color: Colors.textBody;
    }

    if self.is-editing: TextField {
        width: 100%;
        text: Api.format-money-without-symbol(amount);
        input-type: decimal;
        init => {
            self.focus();
        }
        accepted => {
            parent.changed(self.text);
            parent.is-editing = false;
        }
    }
}

component TransactionRow inherits TableRow {
    in property <Transaction> transaction;
    in property <int> length;
    in property <string> active-account-id;

    // FIXME: wrap the whole transaction row in a TouchArea

    right-clicked => {
        context-menu.show();
    }

    padding-left: 8px;
    padding-right: 8px;

    context-menu := ContextMenu {
        min-width: 250px;
        ContextMenuItem {
            text: @tr("Duplicate");
            clicked => {
                State.duplicate-transaction(transaction.id);
                parent.close();
            }
        }

        ContextMenuItem {
            text: @tr("Delete");
            clicked => {
                State.delete-transaction(transaction.id);
                parent.close();
            }
        }
    }

    DateCell {
        width: parent.width / length;
        transaction: transaction;
        changed(value) => {
            State.set-transaction-date(transaction.id, value.year + "-" + value.month + "-" + value.day);
        }
    }

    if active-account-id == "": AccountCell {
        width: parent.width / length;
        transaction: transaction;
        options: State.account-options;
        current-value: transaction.account-id;
        changed(value) => {
            State.set-transaction-account(transaction.id,value);
        }
    }

    PayeeCell {
        width: parent.width / length;
        transaction: transaction;
        active-account-id: active-account-id;
        changed(value) => {
            State.set-transaction-payee(transaction.id,value);
        }
    }

    CategoryCell {
        width: parent.width / length;
        transaction: transaction;
        changed(value) => {
            State.set-transaction-category(transaction.id,value);
        }
    }

    NoteCell {
        width: parent.width / length;
        transaction: transaction;
        changed(value) => {
            State.set-transaction-note(transaction.id, value);
        }
    }

    MoneyCell {
        width: parent.width / length;
        amount: outflow();

        function outflow() -> string {
            if transaction.transaction-type == expense {
                return transaction.amount;
            }
            if transaction.transaction-type == income {
                return "";
            }
            if transaction.transaction-type == transfer && transaction.payee-id != active-account-id {
                return transaction.amount;
            }
            return "";
        }

        changed(value) => {
            State.set-transaction-outflow(transaction.id, value);
        }
    }

    MoneyCell {
        amount: inflow();

        function inflow() -> string {
            if transaction.transaction-type == income {
                return transaction.amount;
            }
            if transaction.transaction-type == expense {
                return "";
            }
            if transaction.payee-id == active-account-id && !active-account-id.is-empty {
                return transaction.amount;
            }
            return "";
        }

        changed(value) => {
            State.set-transaction-inflow(transaction.id, value);
        }
    }
}

// TODO: remove the account option and set to active-account-id
component NewTransactionRow inherits VerticalLayout {
    property <Transaction> transaction: {
        id: "placeholder-transaction",
        date: Api.today(),
        account-id: active-account-id.is-empty ? State.accounts[0].id : active-account-id,
        payee-id: "",
        category-id: "",
        transaction-type: expense,
        outflow: "0.00",
        note: "",
        inflow: "",
    };
    in property <string> active-account-id;
    in property <int> length;

    padding-left: 8px;
    padding-right: 8px;

    callback closed();

    TableRow {
        DateCell {
            width: parent.width / length;
            transaction: transaction;
            changed(value) => {
                transaction.date = value.year + "-" + value.month + "-" + value.day;
            }
        }

        if active-account-id.is-empty: AccountCell {
            width: parent.width / length;
            transaction: transaction;
            changed(value) => {
                transaction.account-id = value;
            }
        }

        // TODO: add icon showing direction or Transfer to and Transfer from
        PayeeCell {
            width: parent.width / length;
            transaction: transaction;
            changed(value) => {
                transaction.payee-id = value;
            }
        }

        CategoryCell {
            width: parent.width / length;
            transaction: transaction;
            changed(value) => {
                transaction.category-id = value;
            }
        }

        NoteCell {
            width: parent.width / length;
            transaction: transaction;
            changed(value) => {
                transaction.note = value;
            }
        }

        MoneyCell {
            width: parent.width / length;
            amount: transaction.outflow;
            changed(value) => {
                transaction.outflow = value;
                transaction.inflow = "";
                State.set-transaction-outflow(transaction.id, value);
            }
        }

        MoneyCell {
            width: parent.width / length;
            amount: transaction.inflow;
            changed(value) => {
                transaction.inflow = value;
                transaction.outflow = "";
            }
        }
    }

    HorizontalLayout {
        alignment: end;
        spacing: 8px;
        padding-left: 8px;
        padding-right: 8px;

        PrimaryButton {
            text: @tr("Cancel");
            theme: ghost;
            clicked => closed();
        }

        PrimaryButton {
            text: @tr("Save");
            clicked => {
                State.create_transaction({
                    date: transaction.date,
                    account-id: transaction.account-id,
                    payee-id: transaction.payee-id,
                    category-id: transaction.category-id,
                    outflow: transaction.outflow,
                    note: transaction.note,
                    inflow: transaction.inflow,
                });
                root.closed();
            }
        }

        PrimaryButton {
            text: @tr("Save and add another");
            clicked => {
                State.create_transaction({
                    date: transaction.date,
                    account-id: transaction.account-id,
                    payee-id: transaction.payee-id,
                    category-id: transaction.category-id,
                    outflow: transaction.outflow,
                    note: transaction.note,
                    inflow: transaction.inflow,
                });
            }
        }
    }
}

component TransactionTableHeader inherits TableRow {
    in property <int> length;
    in property <bool> show-account;
    padding-left: 8px;
    padding-right: 8px;

    TableCell {
        width: parent.width / length;

        HorizontalLayout {
            spacing: 8px;
            cross-axis-alignment: center;

            IconDisplay {
                icon: IconSet.Info;
                size: 14px;
                stroke-width: 2;
                stroke: Colors.textBody;
            }

            Text {
                text: @tr("Date");
                color: Colors.textBody;
            }
        }
    }

    if show-account: TableCell {
        width: parent.width / length;
        Text {
            text: @tr("Account");
            color: Colors.textBody;
        }
    }

    TableCell {
        width: parent.width / length;
        Text {
            text: @tr("Payee");
            color: Colors.textBody;
        }
    }

    TableCell {
        width: parent.width / length;
        Text {
            text: @tr("Category");
            color: Colors.textBody;
        }
    }

    TableCell {
        width: parent.width / length;
        Text {
            text: @tr("Note");
            color: Colors.textBody;
        }
    }

    TableCell {
        width: parent.width / length;
        Text {
            text: @tr("Outflow");
            color: Colors.textBody;
        }
    }

    TableCell {
        width: parent.width / length;
        Text {
            text: @tr("Inflow");
            color: Colors.textBody;
        }
    }
}

export component TransactionPage inherits VerticalLayout {
    in property <[Transaction]> transactions;
    in property <string> active-account-id;
    property <bool> new-transaction-active: false;
    property <data-transfer> csv-data;

    VerticalLayout {
        padding: 12px;
        spacing: 4px;

        Text {
            text: active-account-id.is-empty
                ? @tr("All accounts")
                : State.get-account(active-account-id).name;
            color: Colors.textBody;
            font-weight: FontWeight.semi-bold;
        }

        Text {
            text: active-account-id.is-empty
                ? State.format-money(State.total-balance(),Settings.currency-code)
                : State.format-money(State.get-account(active-account-id).balance, Settings.currency-code);
            font-size: FontSize.heading-sm;
            color: Colors.textHeading;
            font-weight: FontWeight.semi-bold;
        }
    }

    import-csv-dialog := ImportCsvDialog {
        x: Api.window-size().width * 0.5 - self.width * 0.5 - root.absolute-position.x;
        y: Api.window-size().height * 0.5 - self.height * 0.5;
        data: csv-data;
        account-id: active-account-id;
    }

    HorizontalLayout {
        alignment: end;
        cross-axis-alignment: center;
        padding-left: 16px;
        padding-right: 16px;
        padding-top: 8px;
        padding-bottom: 8px;
        spacing: 8px;

        if !active-account-id.is-empty: IconButton {
            icon: IconSet.FileDown;
            theme: ghost;
            accessible-label: @tr("Import CSV file");
            clicked => {
                csv-data = ImportCsvState.open-csv();
                import-csv-dialog.show();
            }
        }

        PrimaryButton {
            text: @tr("New");
            clicked => {
                new-transaction-active = true;
            }
        }
    }

    Table {
        width: 100%;
        property <int> length: active-account-id.is-empty ? 7 : 6;

        Rectangle {
            width: 100%;
            height: 2px;
            background: Colors.neutral50;
        }

        TransactionTableHeader {
            length: length;
            show-account: active-account-id.is-empty;
        }

        if new-transaction-active: NewTransactionRow {
            length: length;
            active-account-id: active-account-id;
            closed => {
                new-transaction-active = false;
            }
        }

        for transaction[index] in transactions: TransactionRow {
            transaction: transaction;
            active-account-id: active-account-id;
            length: length;
            visible: active-account-id.is-empty ? true :
                transaction.account-id == active-account-id || transaction.payee-id == active-account-id;
            height: self.visible ? self.preferred-height : 0;
        }
    }
}
