name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
concurrency:
  cancel-in-progress: true
  group: ${{github.ref}}-${{github.job}}
jobs:
  bench-compile-times:
    strategy:
      fail-fast: false
      matrix:
        rust-flags:
          - "-Zshare-generics=y"
          - "-Zshare-generics=y -Zthreads=8"
          - "-Zshare-generics=y -Zthreads=8 -Clinker=rust-lld.exe -Clink-arg=/FORCE:MULTIPLE"
          - "-Zshare-generics=y -Clinker=rust-lld.exe -Clink-arg=/FORCE:MULTIPLE"
          - "-Zthreads=8 -Clinker=rust-lld.exe -Clink-arg=/FORCE:MULTIPLE"
          - "-Zthreads=8"
          - "-Clinker=rust-lld.exe -Clink-arg=/FORCE:MULTIPLE"
          - ""
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Clean any artifacts
        run: cargo clean
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - run: cargo +nightly build --timings
        env:
          RUSTFLAGS: ${{matrix.rust-flags}}
      - name: Upload cargo build timings
        uses: actions/upload-artifact@v4
        with:
          name: build-timings-${{matrix.rust-flags}}
          path: target/cargo-timings/*.html
  format:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check
  clippy:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev \
          xinput \
          libxcursor-dev \
          libxkbcommon-x11-dev \
          libfontconfig1-dev \
          pkg-config \
          libx11-dev
      - run: cargo clippy --all-targets -- -Dwarnings
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev \
          xinput \
          libxcursor-dev \
          libxkbcommon-x11-dev \
          libfontconfig1-dev \
          pkg-config \
          libx11-dev
      - run: cargo nextest run --locked --no-fail-fast
  doc-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev \
          xinput \
          libxcursor-dev \
          libxkbcommon-x11-dev \
          libfontconfig1-dev \
          pkg-config \
          libx11-dev
      - run: cargo test --doc
