name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
concurrency:
  cancel-in-progress: true
  group: ${{github.ref}}-${{github.job}}
jobs:
  format:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check
  clippy:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v6
        with:
          key: ${{runner.os}}-Rust-${{hashFiles('**/Cargo.toml')}}-${{hashFiles('**/Cargo.lock')}}
          restore-keys: |
            ${{runner.os}}-Rust-${{hashFiles('Cargo.toml')}}-
            ${{runner.os}}-Rust-
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - run: cargo clippy --all-features -- -Dwarnings
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v6
        with:
          key: ${{runner.os}}-Rust-${{hashFiles('**/Cargo.toml')}}-${{hashFiles('**/Cargo.lock')}}
          restore-keys: |
            ${{runner.os}}-Rust-${{hashFiles('Cargo.toml')}}-
            ${{runner.os}}-Rust-
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev \
          xinput \
          libxcursor-dev \
          libxkbcommon-x11-dev \
          libfontconfig1-dev \
          pkg-config \
          libx11-dev
      - run: cargo nextest run --locked --no-fail-fast
  doc-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v6
        with:
          key: ${{runner.os}}-Rust-${{hashFiles('**/Cargo.toml')}}-${{hashFiles('**/Cargo.lock')}}
          restore-keys: |
            ${{runner.os}}-Rust-${{hashFiles('Cargo.toml')}}-
            ${{runner.os}}-Rust-
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev \
          xinput \
          libxcursor-dev \
          libxkbcommon-x11-dev \
          libfontconfig1-dev \
          pkg-config \
          libx11-dev
      - run: cargo test --doc
