name: CI
env:
  JUST_VERSION: 1.46.0
  QT_VERSION: 6.10.0
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
concurrency:
  group: ci-${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true
jobs:
#  lint-qml:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - name: Install Qt
#        uses: jurplel/install-qt-action@v4
#        with:
#          cache: true
#          cache-key-prefix: ${{runner.os}}-install-qt-${{hashFiles('xmake.lua')}}
#          version: ${{env.QT_VERSION}}
#      - uses: extractions/setup-just@v3
#        with:
#          just-version: ${{env.JUST_VERSION}}
#      - run: just check-qml-lint
  format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
        with:
          just-version: ${{env.JUST_VERSION}}
      - name: Install clang-format
        run: brew install clang-format
      - run: just check-format
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v2
        if: ${{runner.os == 'Linux'}}
        with:
          version: latest
          platform: x64
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          cache-key-prefix: ${{runner.os}}-install-qt-${{hashFiles('xmake.lua')}}
          version: ${{env.QT_VERSION}}
      - name: Set xmake to use Clang
        if: ${{runner.os == 'Linux'}}
        run: xmake f --toolchain=clang -y
      - run: xmake build -y
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v3
        with:
          just-version: ${{env.JUST_VERSION}}
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: sudo apt update
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          cache-key-prefix: ${{runner.os}}-install-qt-${{hashFiles('xmake.lua')}}
          version: ${{env.QT_VERSION}}
      - name: Set xmake to use Clang
        if: ${{runner.os == 'Linux'}}
        run: xmake f --toolchain=clang -y
      - uses: extractions/setup-just@v3
        with:
          just-version: ${{env.JUST_VERSION}}
      - name: Run tests
        run: just test
  pass:
    needs:
      - test
      - build
      - format
#      - lint-qml
    runs-on: ubuntu-latest
    steps:
      - name: Complete
        run: echo All good!
