name: Release
on:
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: release-mukwa
env:
  CARGO_TERM_COLOR: always
jobs:
  bundle-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: hustcer/setup-nu@v3
        with:
          version: 0.114.1
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev \
          xinput \
          libxcursor-dev \
          libxkbcommon-x11-dev \
          libfontconfig1-dev \
          pkg-config \
          libx11-dev
      - name: Bundle app
        env:
          ARCHITECTURE: x86_64
        run: nu scripts/bundle-appimage.nu
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mukwa-upload-${{ runner.os }}
          path: build/*.AppImage
  bundle-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Bundle app
        run: scripts/bundle-windows.ps1
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mukwa-upload-${{ runner.os }}
          path: build/*-Setup.exe
  release:
    permissions:
      contents: write
    needs:
      - bundle-linux
      - bundle-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          pattern: mukwa-upload-*
          merge-multiple: true
          path: artifacts
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          name: Mukwa vx.x.x
          body_path: CHANGELOG.md
          files: |
            artifacts/**/*
            CHANGELOG.md
          draft: true
